/** Basket 模块常量与错误码 */

export const BASKET_OPS_QUEUE = 'basket-ops'

export const BASKET_EXECUTION_ADAPTER_TOKEN = 'BASKET_EXECUTION_ADAPTER'

export const BASKET_ERROR_CODES = {
  STRATEGY_NOT_FOUND: 'BASKET_STRATEGY_NOT_FOUND',
  STRATEGY_VERSION_NOT_FOUND: 'BASKET_STRATEGY_VERSION_NOT_FOUND',
  NO_ACTIVE_VERSION: 'BASKET_NO_ACTIVE_VERSION',
  ALLOCATION_EMPTY: 'BASKET_ALLOCATION_EMPTY',
  PORTFOLIO_NOT_FOUND: 'BASKET_PORTFOLIO_NOT_FOUND',
  PORTFOLIO_NOT_ACTIVE: 'BASKET_PORTFOLIO_NOT_ACTIVE',
  NAV_UNAVAILABLE: 'BASKET_NAV_UNAVAILABLE',
  DISCLOSURE_ACK_REQUIRED: 'BASKET_DISCLOSURE_ACK_REQUIRED',
  AMOUNT_INVALID: 'BASKET_AMOUNT_INVALID',
  UNITS_INVALID: 'BASKET_UNITS_INVALID',
  INSUFFICIENT_UNITS: 'BASKET_INSUFFICIENT_UNITS',
  MEMBERSHIP_REQUIRED: 'BASKET_MEMBERSHIP_REQUIRED',
  REBALANCE_RUN_NOT_FOUND: 'BASKET_REBALANCE_RUN_NOT_FOUND',
  REBALANCE_RUN_NOT_EXECUTABLE: 'BASKET_REBALANCE_RUN_NOT_EXECUTABLE',
  ORDER_NOT_FOUND: 'BASKET_ORDER_NOT_FOUND',
  ORDER_NOT_FILLABLE: 'BASKET_ORDER_NOT_FILLABLE',
  EXECUTION_DISABLED: 'BASKET_EXECUTION_DISABLED',
  RISK_BLOCKED: 'BASKET_RISK_BLOCKED',
  RECONCILIATION_INPUT_INVALID: 'BASKET_RECONCILIATION_INPUT_INVALID',
} as const

export const BASKET_DEFAULTS = {
  driftThresholdPct: 5,
  minTradeUsd: 10,
  maxAssetWeightPct: 35,
  maxIssuerWeightPct: 40,
  cashBufferPct: 5,
  maxSlippagePct: 1.5,
  redemptionFeePct: 0,
} as const

/** 账本余额不足（触发器 23514 / 消息）→ 业务层降级为 409 */
export function isInsufficientLedgerBalance(error: unknown): boolean {
  if (error instanceof Error && /insufficient balance/i.test(error.message)) return true
  return typeof error === 'object' && error !== null && (error as { code?: string }).code === '23514'
}
