import type { AppLocale } from './i18n'

type AssetCopy = {
  compute: { overline: string; narrative: string; bullets: [string, string, string] }
  stocks: { overline: string; narrative: string; bullets: [string, string, string]; provider: string; legal: string; returns: string; exit: string }
  prediction: { overline: string; narrative: string; bullets: [string, string, string]; provider: string; legal: string; returns: string; exit: string }
  actualProvider: string; legalForm: string; returnSource: string; exitRule: string; disclosure: string; previewFlow: string
}

const en: AssetCopy = {
  compute: { overline: 'AI COMPUTE MARKETPLACE', narrative: 'Acquire a revenue share in GPU capacity reserved for enterprise AI inference and training workloads.', bullets: ['Daily USDT revenue accrual', 'Live utilization telemetry', 'No hardware custody required'] },
  stocks: { overline: 'GLOBAL EQUITIES', narrative: 'A USDT-settled route to a curated technology equity basket led by NVIDIA.', bullets: ['AI analyst thesis and risk factors', 'Transparent reference price', 'Exit during supported market windows'], provider: 'Licensed broker / tokenized issuer · Demo pending', legal: 'Broker distribution or tokenized security · pending counsel', returns: 'Reference equity price and applicable corporate actions', exit: 'Supported market hours and available liquidity' },
  prediction: { overline: 'POLYMARKET MARKET DISCOVERY', narrative: 'Browse publicly available prediction market data. Any RWA.LAT order flow remains a Demo until distribution, regional eligibility and user permissions are configured.', bullets: ['Real-time public probability and volume', 'Review resolution criteria before an order', 'Demo presentation does not place an external order'], provider: 'Prediction venue partner · Demo pending', legal: 'Public data discovery; event-contract execution disabled', returns: 'Market price movement and final resolution outcome', exit: 'Sell before resolution when liquidity is available' },
  actualProvider: 'Actual provider', legalForm: 'Legal form', returnSource: 'Return source', exitRule: 'Exit rule', disclosure: 'Returns are projected and not guaranteed. Review the offering documents before allocating.', previewFlow: 'Preview Demo distribution flow',
}

export const assetExperienceCopy: Record<AppLocale, AssetCopy> = {
  en,
  'zh-CN': { compute: { overline: 'AI 算力市场', narrative: '配置面向企业 AI 推理与训练负载的 GPU 算力收益份额。', bullets: ['每日计提 USDT 收益', '实时查看利用率数据', '无需保管实体硬件'] }, stocks: { overline: '全球股票', narrative: '通过 USDT 结算的方式参与以 NVIDIA 为核心的精选科技股票组合。', bullets: ['查看 AI 分析逻辑与风险因素', '透明的参考价格', '在支持的交易时段退出'], provider: '持牌券商 / 代币化发行方 · 演示待定', legal: '券商代销或代币化证券 · 待法律意见', returns: '参考股票价格及适用的公司行动', exit: '支持的交易时段与可用流动性' }, prediction: { overline: 'POLYMARKET 市场发现', narrative: '浏览公开预测市场数据。在分销权限、地区准入与用户权限配置完成前，RWA.LAT 订单流程仅用于演示。', bullets: ['实时公开概率与成交量', '下单前审阅最终判定标准', '演示展示不会发送外部订单'], provider: '预测市场合作方 · 演示待定', legal: '公开数据发现；事件合约执行未启用', returns: '市场价格变化与最终判定结果', exit: '流动性可用时可在最终判定前卖出' }, actualProvider: '实际合作方', legalForm: '法律形态', returnSource: '收益来源', exitRule: '退出规则', disclosure: '预计收益不构成保证，配置前请审阅发行文件。', previewFlow: '预览演示分销流程' },
  hi: { compute: { overline: 'AI कंप्यूट बाज़ार', narrative: 'एंटरप्राइज़ AI इंफ़रेंस और प्रशिक्षण के लिए आरक्षित GPU क्षमता की आय हिस्सेदारी प्राप्त करें।', bullets: ['दैनिक USDT आय', 'लाइव उपयोग टेलीमेट्री', 'हार्डवेयर कस्टडी आवश्यक नहीं'] }, stocks: { overline: 'वैश्विक इक्विटी', narrative: 'NVIDIA के नेतृत्व वाली तकनीकी शेयर टोकरी तक USDT-निपटान मार्ग।', bullets: ['AI तर्क और जोखिम', 'पारदर्शी संदर्भ मूल्य', 'समर्थित बाज़ार समय में निकास'], provider: 'लाइसेंस प्राप्त ब्रोकर / टोकन जारीकर्ता · डेमो लंबित', legal: 'ब्रोकर वितरण या टोकन सुरक्षा · कानूनी राय लंबित', returns: 'संदर्भ शेयर मूल्य और लागू कॉर्पोरेट कार्रवाई', exit: 'समर्थित बाज़ार समय और उपलब्ध तरलता' }, prediction: { overline: 'POLYMARKET बाज़ार खोज', narrative: 'सार्वजनिक प्रेडिक्शन डेटा देखें। वितरण, क्षेत्रीय पात्रता और अनुमति कॉन्फ़िगर होने तक ऑर्डर प्रवाह केवल डेमो है।', bullets: ['लाइव सार्वजनिक संभावना और मात्रा', 'ऑर्डर से पहले समाधान मानदंड देखें', 'डेमो बाहरी ऑर्डर नहीं भेजता'], provider: 'प्रेडिक्शन स्थल साझेदार · डेमो लंबित', legal: 'सार्वजनिक डेटा खोज; इवेंट अनुबंध बंद', returns: 'बाज़ार मूल्य परिवर्तन और अंतिम परिणाम', exit: 'तरलता उपलब्ध होने पर समाधान से पहले बेचें' }, actualProvider: 'वास्तविक प्रदाता', legalForm: 'कानूनी रूप', returnSource: 'प्रतिफल स्रोत', exitRule: 'निकास नियम', disclosure: 'अनुमानित प्रतिफल की गारंटी नहीं है। आवंटन से पहले दस्तावेज़ पढ़ें।', previewFlow: 'डेमो वितरण प्रवाह देखें' },
  es: { compute: { overline: 'MERCADO DE CÓMPUTO IA', narrative: 'Adquiere una participación en ingresos de capacidad GPU reservada para inferencia y entrenamiento empresarial.', bullets: ['Ingreso diario en USDT', 'Telemetría de utilización en vivo', 'Sin custodia de hardware'] }, stocks: { overline: 'RENTA VARIABLE GLOBAL', narrative: 'Ruta liquidada en USDT a una cesta tecnológica liderada por NVIDIA.', bullets: ['Tesis IA y factores de riesgo', 'Precio de referencia transparente', 'Salida en horarios compatibles'], provider: 'Broker autorizado / emisor tokenizado · Demo pendiente', legal: 'Distribución de broker o valor tokenizado · pendiente de asesoría', returns: 'Precio de referencia y acciones corporativas aplicables', exit: 'Horario compatible y liquidez disponible' }, prediction: { overline: 'DESCUBRIMIENTO POLYMARKET', narrative: 'Consulta datos públicos de predicción. El flujo seguirá siendo Demo hasta configurar distribución, elegibilidad y permisos.', bullets: ['Probabilidad y volumen públicos en vivo', 'Revisa los criterios de resolución', 'La Demo no envía órdenes externas'], provider: 'Socio de mercado predictivo · Demo pendiente', legal: 'Descubrimiento de datos; ejecución de contratos desactivada', returns: 'Movimiento de precio y resultado de resolución', exit: 'Venta antes de la resolución si hay liquidez' }, actualProvider: 'Proveedor real', legalForm: 'Forma legal', returnSource: 'Fuente de rendimiento', exitRule: 'Regla de salida', disclosure: 'Los rendimientos son proyectados y no están garantizados. Revisa los documentos.', previewFlow: 'Ver flujo de distribución Demo' },
  ar: { compute: { overline: 'سوق حوسبة الذكاء الاصطناعي', narrative: 'احصل على حصة إيراد من سعة GPU المخصصة لاستدلال وتدريب الذكاء الاصطناعي للمؤسسات.', bullets: ['استحقاق يومي بـ USDT', 'بيانات استخدام مباشرة', 'لا حاجة لحفظ أجهزة'] }, stocks: { overline: 'الأسهم العالمية', narrative: 'مسار مسوى بـ USDT إلى سلة أسهم تقنية تقودها NVIDIA.', bullets: ['منطق محلل الذكاء الاصطناعي والمخاطر', 'سعر مرجعي شفاف', 'خروج خلال ساعات السوق المدعومة'], provider: 'وسيط مرخص / مُصدر مرمز · العرض معلق', legal: 'توزيع وسيط أو ورقة مالية مرمزة · الرأي القانوني معلق', returns: 'سعر السهم المرجعي وإجراءات الشركات', exit: 'ساعات السوق المدعومة والسيولة المتاحة' }, prediction: { overline: 'اكتشاف أسواق POLYMARKET', narrative: 'تصفح بيانات أسواق التوقعات العامة. يبقى سير الطلب تجريبيًا حتى ضبط التوزيع والأهلية والأذونات.', bullets: ['احتمال وحجم عامان مباشران', 'راجع معايير الحسم قبل الطلب', 'العرض لا يرسل طلبًا خارجيًا'], provider: 'شريك سوق توقعات · العرض معلق', legal: 'اكتشاف بيانات عامة؛ تنفيذ عقود الأحداث معطل', returns: 'حركة سعر السوق ونتيجة الحسم', exit: 'البيع قبل الحسم عند توفر السيولة' }, actualProvider: 'المزود الفعلي', legalForm: 'الشكل القانوني', returnSource: 'مصدر العائد', exitRule: 'قاعدة الخروج', disclosure: 'العوائد متوقعة وغير مضمونة. راجع مستندات الطرح قبل التخصيص.', previewFlow: 'معاينة سير التوزيع التجريبي' },
  fr: { compute: { overline: 'MARCHÉ DU CALCUL IA', narrative: 'Obtenez une part des revenus de capacité GPU réservée à l’inférence et à l’entraînement des entreprises.', bullets: ['Revenu quotidien en USDT', 'Télémétrie d’utilisation en direct', 'Aucune garde de matériel'] }, stocks: { overline: 'ACTIONS MONDIALES', narrative: 'Une voie réglée en USDT vers un panier technologique mené par NVIDIA.', bullets: ['Thèse IA et facteurs de risque', 'Prix de référence transparent', 'Sortie pendant les horaires pris en charge'], provider: 'Courtier agréé / émetteur tokenisé · Démo en attente', legal: 'Distribution courtier ou titre tokenisé · avis juridique en attente', returns: 'Cours de référence et opérations sur titres applicables', exit: 'Horaires pris en charge et liquidité disponible' }, prediction: { overline: 'DÉCOUVERTE POLYMARKET', narrative: 'Consultez les données publiques. Le flux reste en Démo jusqu’à la configuration de la distribution, de l’éligibilité et des autorisations.', bullets: ['Probabilité et volume publics en direct', 'Examiner les critères de résolution', 'La Démo n’envoie aucun ordre externe'], provider: 'Partenaire marché prédictif · Démo en attente', legal: 'Découverte publique ; exécution de contrats désactivée', returns: 'Variation du prix et résultat de résolution', exit: 'Vente avant résolution si la liquidité le permet' }, actualProvider: 'Prestataire réel', legalForm: 'Forme juridique', returnSource: 'Source du rendement', exitRule: 'Règle de sortie', disclosure: 'Les rendements sont projetés et non garantis. Consultez les documents.', previewFlow: 'Aperçu du flux de distribution Démo' },
  pt: { compute: { overline: 'MERCADO DE COMPUTAÇÃO DE IA', narrative: 'Adquira participação na receita de capacidade GPU reservada para inferência e treinamento empresarial.', bullets: ['Receita diária em USDT', 'Telemetria de utilização ao vivo', 'Sem custódia de hardware'] }, stocks: { overline: 'AÇÕES GLOBAIS', narrative: 'Rota liquidada em USDT para uma cesta tecnológica liderada pela NVIDIA.', bullets: ['Tese de IA e fatores de risco', 'Preço de referência transparente', 'Saída em horários compatíveis'], provider: 'Corretora licenciada / emissor tokenizado · Demo pendente', legal: 'Distribuição por corretora ou valor tokenizado · análise jurídica pendente', returns: 'Preço de referência e eventos corporativos aplicáveis', exit: 'Horários compatíveis e liquidez disponível' }, prediction: { overline: 'DESCOBERTA POLYMARKET', narrative: 'Consulte dados públicos. O fluxo permanece Demo até configurar distribuição, elegibilidade e permissões.', bullets: ['Probabilidade e volume públicos ao vivo', 'Revise os critérios de resolução', 'A Demo não envia ordens externas'], provider: 'Parceiro de mercado preditivo · Demo pendente', legal: 'Descoberta pública; execução de contratos desativada', returns: 'Movimento do preço e resultado final', exit: 'Venda antes da resolução quando houver liquidez' }, actualProvider: 'Provedor real', legalForm: 'Forma jurídica', returnSource: 'Fonte do retorno', exitRule: 'Regra de saída', disclosure: 'Os retornos são projetados e não garantidos. Revise os documentos.', previewFlow: 'Ver fluxo de distribuição Demo' },
}
