'use client'

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type AppLocale = 'en' | 'zh-CN' | 'hi' | 'es' | 'ar' | 'fr' | 'pt'

export const localeOptions: Array<{ code: AppLocale; label: string; direction: 'ltr' | 'rtl' }> = [
  { code: 'en', label: 'English', direction: 'ltr' },
  { code: 'zh-CN', label: '简体中文', direction: 'ltr' },
  { code: 'hi', label: 'हिन्दी', direction: 'ltr' },
  { code: 'es', label: 'Español', direction: 'ltr' },
  { code: 'ar', label: 'العربية', direction: 'rtl' },
  { code: 'fr', label: 'Français', direction: 'ltr' },
  { code: 'pt', label: 'Português', direction: 'ltr' },
]

const en = {
  'nav.home': 'Home', 'nav.invest': 'Invest', 'nav.portfolio': 'Portfolio', 'nav.wallet': 'Wallet', 'nav.ai': 'AI advisor',
  'common.demo': 'Demo', 'common.refresh': 'Refresh', 'common.viewAll': 'View all', 'common.back': 'Back', 'common.save': 'Save preferences', 'common.language': 'Language', 'common.languagesCount': '7 languages',
  'home.totalPortfolio': 'Total Portfolio', 'home.aiScore': 'AI Portfolio Score', 'home.marketBrief': 'AI Market Brief', 'home.marketBriefBody': 'Compute demand is accelerating.', 'home.explore': 'Explore Opportunities', 'home.snapshot': 'Market snapshot', 'home.actions': "Today's actions", 'home.income': 'Income calendar',
  'invest.title': 'Invest', 'invest.search': 'Search opportunities', 'invest.filters': 'Filters', 'invest.execution': 'Execution desk', 'invest.noResults': 'No matching opportunities',
  'invest.refine': 'Refine opportunities', 'invest.matchCount': '{count} products match', 'invest.reset': 'Reset', 'invest.riskLevel': 'Risk level', 'invest.allRisk': 'All risk levels', 'invest.low': 'Low', 'invest.medium': 'Medium', 'invest.high': 'High', 'invest.availability': 'Availability', 'invest.anyStatus': 'Any status', 'invest.openNow': 'Open now', 'invest.limited': 'Limited capacity', 'invest.minimum': 'Minimum allocation', 'invest.anyAmount': 'Any amount', 'invest.showCount': 'Show {count} opportunities', 'invest.featured': 'Featured', 'invest.yieldHigh': 'Yield: high to low', 'invest.minimumLow': 'Minimum: low to high', 'invest.riskLow': 'Risk: low to high', 'invest.sortTitle': 'Sort opportunities', 'invest.sortBody': 'Choose the order that fits your review', 'invest.featuredBody': 'Curated platform order', 'invest.yieldBody': 'Projected or indicative metric', 'invest.minimumBody': 'Start with lower allocations', 'invest.riskBody': 'Review lower-risk labels first', 'invest.closeOptions': 'Close options',
  'portfolio.title': 'Portfolio', 'portfolio.total': 'Total invested', 'portfolio.allocation': 'Allocation', 'portfolio.askAi': 'Ask AI',
  'wallet.title': 'Wallet', 'wallet.deposit': 'Deposit', 'wallet.withdraw': 'Withdraw', 'wallet.transfer': 'Transfer', 'wallet.fiat': 'Fiat soon', 'wallet.assets': 'Assets', 'wallet.activity': 'Activity',
  'profile.title': 'Profile', 'profile.verified': 'Verified investor', 'profile.identity': 'Identity & KYC', 'profile.security': 'Security & devices', 'profile.referral': 'Referral rewards', 'profile.records': 'Transaction records', 'profile.support': 'Support center', 'profile.marketing': 'Marketing preferences', 'profile.official': 'Official channels', 'profile.trust': 'Trust & disclosures', 'profile.settings': 'Settings', 'profile.signout': 'Sign out of RWA.LAT',
  'auth.hero': 'Global assets. One intelligent wallet.', 'auth.body': 'Invest with USDT across compute, real-world assets, stocks and prediction markets.', 'auth.start': 'Get started', 'auth.guest': 'Explore as guest', 'auth.login': 'Welcome to RWA.LAT', 'auth.register': 'Create your account', 'auth.email': 'Continue with email', 'auth.google': 'Continue with Google', 'auth.x': 'Continue with X', 'auth.wallet': 'Sign with wallet',
  'settings.language': 'Language', 'settings.notifications': 'Market notifications', 'settings.marketing': 'Marketing preferences', 'settings.fiat': 'Fiat entry',
  'marketing.title': 'Marketing preferences', 'marketing.heading': 'You decide what reaches you.', 'marketing.body': 'Control research, product and event updates independently from essential account messages.', 'marketing.email': 'Research & product email', 'marketing.push': 'Market and event push', 'marketing.community': 'Community invitations', 'marketing.unsubscribe': 'Unsubscribe from all marketing', 'marketing.saved': 'Marketing preferences saved in this Demo.',
  'official.title': 'Official channels', 'official.heading': 'Verify before you trust.', 'official.body': 'RWA.LAT never asks for seed phrases, private keys, verification codes or transfers to a personal address.', 'official.domain': 'Official domain', 'official.social': 'Verified social accounts', 'official.report': 'Report impersonation or scam',
  'scam.title': 'Report a scam', 'scam.heading': 'Help us investigate safely.', 'scam.body': 'Submit the suspicious account, URL or wallet address. Never include a seed phrase or private key.', 'scam.source': 'Suspicious account, URL or wallet', 'scam.details': 'What happened?', 'scam.submit': 'Create Demo report',
  'guest.badge': 'Guest', 'guest.signin': 'Sign in to continue', 'guest.protected': 'This action requires a secure account. Public product browsing remains available.',
  'risk.aiTitle': 'AI decision acknowledgement', 'risk.aiBody': 'AI output may be incomplete or wrong. It is not a guarantee of return or a substitute for legal, tax or licensed investment advice.',
  'trust.title': 'Trust center', 'trust.eyebrow': 'TRUST CENTER', 'trust.heading': 'Know who, what and where before you invest.', 'trust.body': 'Review access rules, product structures, fees, legal documents, support routes and verified channels in one place.',
  'trust.access': 'Access and regions', 'trust.accessBody': 'Guest rules, country checks and product restrictions', 'trust.products': 'Product disclosures', 'trust.productsBody': 'Issuer, return source, fees, maturity and exit', 'trust.legal': 'Legal document center', 'trust.legalBody': 'Terms, privacy, risk and consent versions', 'trust.supportBody': 'Create and track an investment or payment case',
  'trust.demoNote': 'Demo content supports product review. Partner names, licences, eligibility rules and offering documents require approval before real execution.',
} as const

type TranslationKey = keyof typeof en
type Dictionary = Partial<Record<TranslationKey, string>>

const dictionaries: Record<AppLocale, Dictionary> = {
  en,
  'zh-CN': {
    'nav.home': '首页', 'nav.invest': '投资', 'nav.portfolio': '资产组合', 'nav.wallet': '钱包', 'nav.ai': 'AI 助手',
    'common.demo': '演示', 'common.refresh': '刷新', 'common.viewAll': '查看全部', 'common.back': '返回', 'common.save': '保存偏好', 'common.language': '语言', 'common.languagesCount': '支持 7 种语言',
    'home.totalPortfolio': '总资产', 'home.aiScore': 'AI 组合评分', 'home.marketBrief': 'AI 市场简报', 'home.marketBriefBody': '算力需求正在加速。', 'home.explore': '探索投资机会', 'home.snapshot': '市场概览', 'home.actions': '今日事项', 'home.income': '收益日历',
    'invest.title': '投资', 'invest.search': '搜索投资机会', 'invest.filters': '筛选', 'invest.execution': '执行中心', 'invest.noResults': '没有匹配的产品',
    'invest.refine': '筛选投资机会', 'invest.matchCount': '找到 {count} 个产品', 'invest.reset': '重置', 'invest.riskLevel': '风险等级', 'invest.allRisk': '全部风险等级', 'invest.low': '低风险', 'invest.medium': '中风险', 'invest.high': '高风险', 'invest.availability': '可认购状态', 'invest.anyStatus': '全部状态', 'invest.openNow': '当前开放', 'invest.limited': '额度有限', 'invest.minimum': '最低认购额', 'invest.anyAmount': '不限金额', 'invest.showCount': '查看 {count} 个机会', 'invest.featured': '精选排序', 'invest.yieldHigh': '收益指标从高到低', 'invest.minimumLow': '最低认购额从低到高', 'invest.riskLow': '风险从低到高', 'invest.sortTitle': '投资机会排序', 'invest.sortBody': '选择适合你的浏览顺序', 'invest.featuredBody': '平台精选的默认顺序', 'invest.yieldBody': '按预计或指示性指标排序', 'invest.minimumBody': '优先查看低门槛产品', 'invest.riskBody': '优先查看较低风险标签', 'invest.closeOptions': '关闭选项',
    'portfolio.title': '资产组合', 'portfolio.total': '已投资总额', 'portfolio.allocation': '资产配置', 'portfolio.askAi': '咨询 AI',
    'wallet.title': '钱包', 'wallet.deposit': '充值', 'wallet.withdraw': '提现', 'wallet.transfer': '转账', 'wallet.fiat': '法币即将上线', 'wallet.assets': '资产', 'wallet.activity': '交易记录',
    'profile.title': '个人中心', 'profile.verified': '已认证投资者', 'profile.identity': '身份与 KYC', 'profile.security': '安全与设备', 'profile.referral': '邀请奖励', 'profile.records': '交易记录', 'profile.support': '客服中心', 'profile.marketing': '营销偏好', 'profile.official': '官方渠道验证', 'profile.trust': '信任与披露中心', 'profile.settings': '设置', 'profile.signout': '退出 RWA.LAT',
    'auth.hero': '全球资产，一个智能钱包。', 'auth.body': '使用 USDT 参与 AI 算力、真实世界资产、股票和预测市场。', 'auth.start': '开始使用', 'auth.guest': '以访客身份浏览', 'auth.login': '欢迎回到 RWA.LAT', 'auth.register': '创建账户', 'auth.email': '使用邮箱继续', 'auth.google': '使用 Google 继续', 'auth.x': '使用 X 继续', 'auth.wallet': '钱包签名登录',
    'settings.language': '语言', 'settings.notifications': '市场通知', 'settings.marketing': '营销偏好', 'settings.fiat': '法币入口',
    'marketing.title': '营销偏好', 'marketing.heading': '由你决定接收什么。', 'marketing.body': '研究、产品和活动消息可独立控制，不影响必要的账户与安全通知。', 'marketing.email': '研究与产品邮件', 'marketing.push': '市场与活动推送', 'marketing.community': '社群活动邀请', 'marketing.unsubscribe': '退订全部营销消息', 'marketing.saved': 'Demo 营销偏好已保存。',
    'official.title': '官方渠道', 'official.heading': '先验证，再信任。', 'official.body': 'RWA.LAT 不会索取助记词、私钥、验证码，也不会要求向个人地址转账。', 'official.domain': '官方网站', 'official.social': '官方社交账号', 'official.report': '举报冒充或诈骗',
    'scam.title': '举报诈骗', 'scam.heading': '安全提交线索。', 'scam.body': '提交可疑账号、网址或钱包地址，请勿填写助记词或私钥。', 'scam.source': '可疑账号、网址或钱包地址', 'scam.details': '发生了什么？', 'scam.submit': '创建 Demo 举报',
    'guest.badge': '访客', 'guest.signin': '登录后继续', 'guest.protected': '该操作需要安全账户，公开产品仍可继续浏览。',
    'risk.aiTitle': 'AI 决策确认', 'risk.aiBody': 'AI 输出可能不完整或错误，不保证收益，也不能替代法律、税务或持牌投资建议。',
    'trust.title': '信任中心', 'trust.eyebrow': '信任与透明', 'trust.heading': '投资之前，先确认主体、产品与适用地区。', 'trust.body': '集中查看准入规则、产品结构、费用、法律文件、客服路径与官方渠道。',
    'trust.access': '准入与可用地区', 'trust.accessBody': '访客规则、国家核验与产品限制', 'trust.products': '产品披露', 'trust.productsBody': '发行方、收益来源、费用、期限与退出', 'trust.legal': '法律文件中心', 'trust.legalBody': '条款、隐私、风险与同意版本', 'trust.supportBody': '创建并追踪投资、订单或支付争议',
    'trust.demoNote': '演示内容仅用于产品审阅。真实执行前须核准合作方、牌照、准入规则及发行文件。',
  },
  hi: {
    'nav.home': 'होम', 'nav.invest': 'निवेश', 'nav.portfolio': 'पोर्टफोलियो', 'nav.wallet': 'वॉलेट', 'nav.ai': 'AI सलाहकार',
    'common.demo': 'डेमो', 'common.refresh': 'रीफ़्रेश', 'common.viewAll': 'सभी देखें', 'common.back': 'वापस', 'common.save': 'प्राथमिकताएँ सहेजें', 'common.language': 'भाषा',
    'home.totalPortfolio': 'कुल पोर्टफोलियो', 'home.aiScore': 'AI पोर्टफोलियो स्कोर', 'home.marketBrief': 'AI मार्केट ब्रीफ', 'home.marketBriefBody': 'कंप्यूट मांग तेज़ हो रही है।', 'home.explore': 'अवसर देखें', 'home.snapshot': 'बाज़ार का सार', 'home.actions': 'आज के कार्य', 'home.income': 'आय कैलेंडर',
    'invest.title': 'निवेश', 'invest.search': 'अवसर खोजें', 'invest.execution': 'निष्पादन केंद्र', 'invest.noResults': 'कोई मेल खाता उत्पाद नहीं', 'portfolio.title': 'पोर्टफोलियो', 'portfolio.total': 'कुल निवेश', 'portfolio.allocation': 'आवंटन', 'portfolio.askAi': 'AI से पूछें', 'wallet.title': 'वॉलेट', 'wallet.deposit': 'जमा', 'wallet.withdraw': 'निकासी', 'wallet.transfer': 'ट्रांसफर', 'wallet.fiat': 'फ़िएट जल्द उपलब्ध', 'wallet.assets': 'परिसंपत्तियाँ', 'wallet.activity': 'गतिविधि',
    'common.languagesCount': '7 भाषाएँ', 'invest.filters': 'फ़िल्टर', 'invest.refine': 'अवसरों को छाँटें', 'invest.matchCount': '{count} उत्पाद मिले', 'invest.reset': 'रीसेट', 'invest.riskLevel': 'जोखिम स्तर', 'invest.allRisk': 'सभी जोखिम स्तर', 'invest.low': 'कम', 'invest.medium': 'मध्यम', 'invest.high': 'उच्च', 'invest.availability': 'उपलब्धता', 'invest.anyStatus': 'कोई भी स्थिति', 'invest.openNow': 'अभी उपलब्ध', 'invest.limited': 'सीमित क्षमता', 'invest.minimum': 'न्यूनतम निवेश', 'invest.anyAmount': 'कोई भी राशि', 'invest.showCount': '{count} अवसर दिखाएँ', 'invest.featured': 'चुनिंदा', 'invest.yieldHigh': 'प्रतिफल: अधिक से कम', 'invest.minimumLow': 'न्यूनतम: कम से अधिक', 'invest.riskLow': 'जोखिम: कम से अधिक', 'invest.sortTitle': 'अवसर क्रमबद्ध करें', 'invest.sortBody': 'अपनी समीक्षा के लिए उपयुक्त क्रम चुनें', 'invest.featuredBody': 'प्लेटफ़ॉर्म द्वारा चुना गया क्रम', 'invest.yieldBody': 'अनुमानित या सांकेतिक संकेतक', 'invest.minimumBody': 'कम निवेश राशि से शुरू करें', 'invest.riskBody': 'कम जोखिम वाले विकल्प पहले देखें', 'invest.closeOptions': 'विकल्प बंद करें',
    'profile.title': 'प्रोफ़ाइल', 'profile.verified': 'सत्यापित निवेशक', 'profile.identity': 'पहचान और KYC', 'profile.security': 'सुरक्षा और डिवाइस', 'profile.referral': 'रेफरल पुरस्कार', 'profile.records': 'लेन-देन अभिलेख', 'profile.support': 'सहायता केंद्र', 'profile.marketing': 'मार्केटिंग प्राथमिकताएँ', 'profile.official': 'आधिकारिक चैनल', 'profile.settings': 'सेटिंग्स', 'profile.signout': 'RWA.LAT से साइन आउट करें',
    'auth.hero': 'वैश्विक संपत्तियाँ। एक बुद्धिमान वॉलेट।', 'auth.body': 'USDT से कंप्यूट, वास्तविक संपत्ति, स्टॉक और प्रेडिक्शन मार्केट तक पहुँचें।', 'auth.start': 'शुरू करें', 'auth.guest': 'अतिथि के रूप में देखें', 'auth.login': 'RWA.LAT में आपका स्वागत है', 'auth.register': 'अपना खाता बनाएँ', 'auth.email': 'ईमेल से जारी रखें', 'auth.google': 'Google से जारी रखें', 'auth.x': 'X से जारी रखें', 'auth.wallet': 'वॉलेट से हस्ताक्षर करें',
    'settings.language': 'भाषा', 'settings.notifications': 'बाज़ार सूचनाएँ', 'settings.marketing': 'मार्केटिंग प्राथमिकताएँ', 'settings.fiat': 'फ़िएट प्रवेश',
    'marketing.title': 'मार्केटिंग प्राथमिकताएँ', 'marketing.heading': 'आप तय करें कि क्या प्राप्त करना है।', 'marketing.body': 'आवश्यक खाता संदेशों से अलग शोध, उत्पाद और कार्यक्रम अपडेट नियंत्रित करें।', 'marketing.email': 'शोध और उत्पाद ईमेल', 'marketing.push': 'बाज़ार और कार्यक्रम पुश', 'marketing.community': 'समुदाय आमंत्रण', 'marketing.unsubscribe': 'सभी मार्केटिंग से सदस्यता हटाएँ', 'marketing.saved': 'डेमो मार्केटिंग प्राथमिकताएँ सहेजी गईं।',
    'official.title': 'आधिकारिक चैनल', 'official.heading': 'भरोसा करने से पहले सत्यापित करें।', 'official.body': 'RWA.LAT कभी भी सीड फ़्रेज़, निजी कुंजी, सत्यापन कोड या निजी पते पर ट्रांसफर नहीं माँगता।', 'official.domain': 'आधिकारिक डोमेन', 'official.social': 'सत्यापित सोशल खाते', 'official.report': 'नकल या धोखाधड़ी रिपोर्ट करें',
    'scam.title': 'धोखाधड़ी की रिपोर्ट करें', 'scam.heading': 'सुरक्षित जाँच में हमारी मदद करें।', 'scam.body': 'संदिग्ध खाता, URL या वॉलेट पता भेजें। सीड फ़्रेज़ या निजी कुंजी कभी न दें।', 'scam.source': 'संदिग्ध खाता, URL या वॉलेट', 'scam.details': 'क्या हुआ?', 'scam.submit': 'डेमो रिपोर्ट बनाएँ', 'guest.badge': 'अतिथि', 'guest.signin': 'जारी रखने के लिए साइन इन करें', 'guest.protected': 'इस कार्य के लिए सुरक्षित खाता चाहिए। सार्वजनिक उत्पाद ब्राउज़िंग उपलब्ध है।', 'profile.trust': 'विश्वास और प्रकटीकरण',
    'risk.aiTitle': 'AI निर्णय स्वीकारोक्ति', 'risk.aiBody': 'AI आउटपुट अधूरा या गलत हो सकता है। यह प्रतिफल की गारंटी या कानूनी, कर अथवा लाइसेंस प्राप्त सलाह का विकल्प नहीं है।',
    'trust.title': 'विश्वास केंद्र', 'trust.eyebrow': 'विश्वास केंद्र', 'trust.heading': 'निवेश से पहले जानें—कौन, क्या और कहाँ।', 'trust.body': 'पात्रता नियम, उत्पाद संरचना, शुल्क, कानूनी दस्तावेज़, सहायता और सत्यापित चैनल एक ही स्थान पर देखें।', 'trust.access': 'पात्रता और क्षेत्र', 'trust.accessBody': 'अतिथि नियम, देश जाँच और उत्पाद प्रतिबंध', 'trust.products': 'उत्पाद प्रकटीकरण', 'trust.productsBody': 'जारीकर्ता, आय स्रोत, शुल्क, अवधि और निकास', 'trust.legal': 'कानूनी दस्तावेज़ केंद्र', 'trust.legalBody': 'शर्तें, गोपनीयता, जोखिम और सहमति संस्करण', 'trust.supportBody': 'निवेश या भुगतान मामला बनाएँ और उसकी स्थिति देखें', 'trust.demoNote': 'यह डेमो सामग्री उत्पाद समीक्षा के लिए है। वास्तविक निष्पादन से पहले भागीदार, लाइसेंस, पात्रता और पेशकश दस्तावेज़ स्वीकृत होने चाहिए।',
  },
  es: {
    'nav.home': 'Inicio', 'nav.invest': 'Invertir', 'nav.portfolio': 'Cartera', 'nav.wallet': 'Billetera', 'nav.ai': 'Asesor IA',
    'common.demo': 'Demo', 'common.refresh': 'Actualizar', 'common.viewAll': 'Ver todo', 'common.back': 'Volver', 'common.save': 'Guardar preferencias', 'common.language': 'Idioma',
    'home.totalPortfolio': 'Cartera total', 'home.aiScore': 'Puntuación IA', 'home.marketBrief': 'Resumen de mercado IA', 'home.marketBriefBody': 'La demanda de cómputo se acelera.', 'home.explore': 'Explorar oportunidades', 'home.snapshot': 'Resumen del mercado', 'home.actions': 'Tareas de hoy', 'home.income': 'Calendario de ingresos',
    'invest.title': 'Invertir', 'invest.search': 'Buscar oportunidades', 'invest.execution': 'Centro de ejecución', 'invest.noResults': 'No hay productos que coincidan', 'portfolio.title': 'Cartera', 'portfolio.total': 'Total invertido', 'portfolio.allocation': 'Distribución', 'portfolio.askAi': 'Consultar a la IA', 'wallet.title': 'Billetera', 'wallet.deposit': 'Depositar', 'wallet.withdraw': 'Retirar', 'wallet.transfer': 'Transferir', 'wallet.fiat': 'Fiat próximamente', 'wallet.assets': 'Activos', 'wallet.activity': 'Actividad',
    'common.languagesCount': '7 idiomas', 'invest.filters': 'Filtros', 'invest.refine': 'Afinar oportunidades', 'invest.matchCount': '{count} productos coinciden', 'invest.reset': 'Restablecer', 'invest.riskLevel': 'Nivel de riesgo', 'invest.allRisk': 'Todos los niveles', 'invest.low': 'Bajo', 'invest.medium': 'Medio', 'invest.high': 'Alto', 'invest.availability': 'Disponibilidad', 'invest.anyStatus': 'Cualquier estado', 'invest.openNow': 'Disponible ahora', 'invest.limited': 'Capacidad limitada', 'invest.minimum': 'Inversión mínima', 'invest.anyAmount': 'Cualquier importe', 'invest.showCount': 'Ver {count} oportunidades', 'invest.featured': 'Destacados', 'invest.yieldHigh': 'Rendimiento: de mayor a menor', 'invest.minimumLow': 'Mínimo: de menor a mayor', 'invest.riskLow': 'Riesgo: de menor a mayor', 'invest.sortTitle': 'Ordenar oportunidades', 'invest.sortBody': 'Elige el orden más útil para tu análisis', 'invest.featuredBody': 'Orden seleccionado por la plataforma', 'invest.yieldBody': 'Métrica prevista o indicativa', 'invest.minimumBody': 'Empieza por importes menores', 'invest.riskBody': 'Consulta primero las etiquetas de menor riesgo', 'invest.closeOptions': 'Cerrar opciones',
    'profile.title': 'Perfil', 'profile.verified': 'Inversor verificado', 'profile.identity': 'Identidad y KYC', 'profile.security': 'Seguridad y dispositivos', 'profile.referral': 'Recompensas', 'profile.records': 'Historial de transacciones', 'profile.support': 'Centro de ayuda', 'profile.marketing': 'Preferencias de marketing', 'profile.official': 'Canales oficiales', 'profile.settings': 'Ajustes', 'profile.signout': 'Cerrar sesión en RWA.LAT',
    'auth.hero': 'Activos globales. Una billetera inteligente.', 'auth.body': 'Invierte con USDT en cómputo, activos reales, acciones y mercados de predicción.', 'auth.start': 'Comenzar', 'auth.guest': 'Explorar como invitado', 'auth.login': 'Bienvenido a RWA.LAT', 'auth.register': 'Crea tu cuenta', 'auth.email': 'Continuar con correo', 'auth.google': 'Continuar con Google', 'auth.x': 'Continuar con X', 'auth.wallet': 'Firmar con billetera',
    'settings.language': 'Idioma', 'settings.notifications': 'Notificaciones de mercado', 'settings.marketing': 'Preferencias de marketing', 'settings.fiat': 'Entrada fiat',
    'marketing.title': 'Preferencias de marketing', 'marketing.heading': 'Tú decides qué recibes.', 'marketing.body': 'Controla investigación, productos y eventos sin afectar los mensajes esenciales de la cuenta.', 'marketing.email': 'Correo de investigación y productos', 'marketing.push': 'Push de mercados y eventos', 'marketing.community': 'Invitaciones de comunidad', 'marketing.unsubscribe': 'Cancelar todo el marketing', 'marketing.saved': 'Preferencias de marketing Demo guardadas.',
    'official.title': 'Canales oficiales', 'official.heading': 'Verifica antes de confiar.', 'official.body': 'RWA.LAT nunca solicita frases semilla, claves privadas, códigos ni transferencias a una dirección personal.', 'official.domain': 'Dominio oficial', 'official.social': 'Cuentas sociales verificadas', 'official.report': 'Reportar suplantación o fraude',
    'scam.title': 'Reportar una estafa', 'scam.heading': 'Ayúdanos a investigar con seguridad.', 'scam.body': 'Envía la cuenta, URL o billetera sospechosa. Nunca incluyas semillas ni claves privadas.', 'scam.source': 'Cuenta, URL o billetera sospechosa', 'scam.details': '¿Qué ocurrió?', 'scam.submit': 'Crear reporte Demo', 'guest.badge': 'Invitado', 'guest.signin': 'Inicia sesión para continuar', 'guest.protected': 'Esta acción requiere una cuenta segura. Los productos públicos siguen disponibles.', 'profile.trust': 'Confianza y divulgaciones',
    'risk.aiTitle': 'Confirmación de decisión IA', 'risk.aiBody': 'La IA puede ser incompleta o errónea. No garantiza rendimientos ni sustituye asesoramiento legal, fiscal o regulado.',
    'trust.title': 'Centro de confianza', 'trust.eyebrow': 'CENTRO DE CONFIANZA', 'trust.heading': 'Conoce quién, qué y dónde antes de invertir.', 'trust.body': 'Consulta en un solo lugar las reglas de acceso, estructuras, comisiones, documentos legales, soporte y canales verificados.', 'trust.access': 'Acceso y regiones', 'trust.accessBody': 'Reglas para invitados, controles por país y restricciones', 'trust.products': 'Divulgaciones de producto', 'trust.productsBody': 'Emisor, fuente de rendimiento, comisiones, vencimiento y salida', 'trust.legal': 'Centro de documentos legales', 'trust.legalBody': 'Términos, privacidad, riesgos y versiones de consentimiento', 'trust.supportBody': 'Crea y sigue un caso de inversión o pago', 'trust.demoNote': 'El contenido Demo sirve para revisar el producto. Los socios, licencias, reglas de acceso y documentos de oferta deben aprobarse antes de cualquier ejecución real.',
  },
  ar: {
    'nav.home': 'الرئيسية', 'nav.invest': 'استثمار', 'nav.portfolio': 'المحفظة', 'nav.wallet': 'المحفظة الرقمية', 'nav.ai': 'مستشار الذكاء الاصطناعي',
    'common.demo': 'عرض تجريبي', 'common.refresh': 'تحديث', 'common.viewAll': 'عرض الكل', 'common.back': 'رجوع', 'common.save': 'حفظ التفضيلات', 'common.language': 'اللغة',
    'home.totalPortfolio': 'إجمالي المحفظة', 'home.aiScore': 'تقييم المحفظة بالذكاء الاصطناعي', 'home.marketBrief': 'موجز السوق', 'home.marketBriefBody': 'الطلب على الحوسبة يتسارع.', 'home.explore': 'استكشف الفرص', 'home.snapshot': 'لمحة السوق', 'home.actions': 'مهام اليوم', 'home.income': 'تقويم الدخل',
    'invest.title': 'استثمار', 'invest.search': 'ابحث عن الفرص', 'invest.execution': 'مركز التنفيذ', 'invest.noResults': 'لا توجد منتجات مطابقة', 'portfolio.title': 'المحفظة', 'portfolio.total': 'إجمالي الاستثمار', 'portfolio.allocation': 'التوزيع', 'portfolio.askAi': 'اسأل الذكاء الاصطناعي', 'wallet.title': 'المحفظة الرقمية', 'wallet.deposit': 'إيداع', 'wallet.withdraw': 'سحب', 'wallet.transfer': 'تحويل', 'wallet.fiat': 'العملات التقليدية قريبًا', 'wallet.assets': 'الأصول', 'wallet.activity': 'النشاط',
    'common.languagesCount': '7 لغات', 'invest.filters': 'التصفية', 'invest.refine': 'تصفية الفرص', 'invest.matchCount': '{count} منتجات مطابقة', 'invest.reset': 'إعادة ضبط', 'invest.riskLevel': 'مستوى المخاطر', 'invest.allRisk': 'جميع مستويات المخاطر', 'invest.low': 'منخفض', 'invest.medium': 'متوسط', 'invest.high': 'مرتفع', 'invest.availability': 'التوافر', 'invest.anyStatus': 'أي حالة', 'invest.openNow': 'متاح الآن', 'invest.limited': 'سعة محدودة', 'invest.minimum': 'الحد الأدنى للاستثمار', 'invest.anyAmount': 'أي مبلغ', 'invest.showCount': 'عرض {count} فرص', 'invest.featured': 'مختارة', 'invest.yieldHigh': 'العائد: من الأعلى إلى الأدنى', 'invest.minimumLow': 'الحد الأدنى: من الأقل إلى الأعلى', 'invest.riskLow': 'المخاطر: من الأقل إلى الأعلى', 'invest.sortTitle': 'ترتيب الفرص', 'invest.sortBody': 'اختر الترتيب الأنسب لمراجعتك', 'invest.featuredBody': 'ترتيب مختار من المنصة', 'invest.yieldBody': 'مؤشر متوقع أو استرشادي', 'invest.minimumBody': 'ابدأ بالمبالغ الأقل', 'invest.riskBody': 'راجع التصنيفات الأقل مخاطرة أولاً', 'invest.closeOptions': 'إغلاق الخيارات',
    'profile.title': 'الملف الشخصي', 'profile.verified': 'مستثمر موثّق', 'profile.identity': 'الهوية والتحقق', 'profile.security': 'الأمان والأجهزة', 'profile.referral': 'مكافآت الإحالة', 'profile.records': 'سجل المعاملات', 'profile.support': 'مركز الدعم', 'profile.marketing': 'تفضيلات التسويق', 'profile.official': 'القنوات الرسمية', 'profile.settings': 'الإعدادات', 'profile.signout': 'تسجيل الخروج من RWA.LAT',
    'auth.hero': 'أصول عالمية. محفظة ذكية واحدة.', 'auth.body': 'استثمر باستخدام USDT في الحوسبة والأصول الواقعية والأسهم وأسواق التوقعات.', 'auth.start': 'ابدأ', 'auth.guest': 'تصفح كضيف', 'auth.login': 'مرحبًا بك في RWA.LAT', 'auth.register': 'أنشئ حسابك', 'auth.email': 'المتابعة بالبريد', 'auth.google': 'المتابعة عبر Google', 'auth.x': 'المتابعة عبر X', 'auth.wallet': 'التوقيع بالمحفظة',
    'settings.language': 'اللغة', 'settings.notifications': 'إشعارات السوق', 'settings.marketing': 'تفضيلات التسويق', 'settings.fiat': 'إدخال العملات التقليدية',
    'marketing.title': 'تفضيلات التسويق', 'marketing.heading': 'أنت تقرر ما يصلك.', 'marketing.body': 'تحكم في تحديثات البحث والمنتجات والفعاليات بصورة مستقلة عن رسائل الحساب الضرورية.', 'marketing.email': 'بريد الأبحاث والمنتجات', 'marketing.push': 'إشعارات السوق والفعاليات', 'marketing.community': 'دعوات المجتمع', 'marketing.unsubscribe': 'إلغاء جميع الرسائل التسويقية', 'marketing.saved': 'تم حفظ تفضيلات التسويق التجريبية.',
    'official.title': 'القنوات الرسمية', 'official.heading': 'تحقق قبل أن تثق.', 'official.body': 'لن تطلب RWA.LAT عبارة الاسترداد أو المفتاح الخاص أو رمز التحقق أو التحويل إلى عنوان شخصي.', 'official.domain': 'النطاق الرسمي', 'official.social': 'حسابات اجتماعية موثقة', 'official.report': 'الإبلاغ عن انتحال أو احتيال',
    'scam.title': 'الإبلاغ عن احتيال', 'scam.heading': 'ساعدنا على التحقيق بأمان.', 'scam.body': 'أرسل الحساب أو الرابط أو عنوان المحفظة المشبوه. لا ترسل عبارة الاسترداد أو المفتاح الخاص.', 'scam.source': 'حساب أو رابط أو محفظة مشبوهة', 'scam.details': 'ماذا حدث؟', 'scam.submit': 'إنشاء بلاغ تجريبي', 'guest.badge': 'ضيف', 'guest.signin': 'سجّل الدخول للمتابعة', 'guest.protected': 'يتطلب هذا الإجراء حسابًا آمنًا. يبقى تصفح المنتجات العامة متاحًا.', 'profile.trust': 'الثقة والإفصاحات',
    'risk.aiTitle': 'إقرار قرار الذكاء الاصطناعي', 'risk.aiBody': 'قد يكون مخرج الذكاء الاصطناعي ناقصًا أو خاطئًا، ولا يضمن العائد ولا يحل محل المشورة القانونية أو الضريبية أو المرخصة.',
    'trust.title': 'مركز الثقة', 'trust.eyebrow': 'مركز الثقة', 'trust.heading': 'اعرف الجهة والمنتج والمنطقة قبل الاستثمار.', 'trust.body': 'راجع قواعد الإتاحة وهياكل المنتجات والرسوم والوثائق القانونية ومسارات الدعم والقنوات الموثقة في مكان واحد.', 'trust.access': 'الإتاحة والمناطق', 'trust.accessBody': 'قواعد الضيف والتحقق حسب الدولة وقيود المنتجات', 'trust.products': 'إفصاحات المنتجات', 'trust.productsBody': 'المُصدر ومصدر العائد والرسوم والاستحقاق والخروج', 'trust.legal': 'مركز الوثائق القانونية', 'trust.legalBody': 'الشروط والخصوصية والمخاطر وإصدارات الموافقة', 'trust.supportBody': 'أنشئ حالة استثمار أو دفع وتابعها', 'trust.demoNote': 'محتوى العرض مخصص لمراجعة المنتج. يجب اعتماد الشركاء والتراخيص وقواعد الإتاحة ووثائق الطرح قبل أي تنفيذ حقيقي.',
  },
  fr: {
    'nav.home': 'Accueil', 'nav.invest': 'Investir', 'nav.portfolio': 'Portefeuille', 'nav.wallet': 'Wallet', 'nav.ai': 'Conseiller IA',
    'common.demo': 'Démo', 'common.refresh': 'Actualiser', 'common.viewAll': 'Tout voir', 'common.back': 'Retour', 'common.save': 'Enregistrer les préférences', 'common.language': 'Langue',
    'home.totalPortfolio': 'Portefeuille total', 'home.aiScore': 'Score IA du portefeuille', 'home.marketBrief': 'Brief marché IA', 'home.marketBriefBody': 'La demande de calcul accélère.', 'home.explore': 'Explorer les opportunités', 'home.snapshot': 'Aperçu du marché', 'home.actions': 'Actions du jour', 'home.income': 'Calendrier des revenus',
    'invest.title': 'Investir', 'invest.search': 'Rechercher des opportunités', 'invest.execution': "Centre d'exécution", 'invest.noResults': 'Aucun produit correspondant', 'portfolio.title': 'Portefeuille', 'portfolio.total': 'Total investi', 'portfolio.allocation': 'Répartition', 'portfolio.askAi': "Demander à l’IA", 'wallet.title': 'Portefeuille', 'wallet.deposit': 'Déposer', 'wallet.withdraw': 'Retirer', 'wallet.transfer': 'Transférer', 'wallet.fiat': 'Fiat bientôt disponible', 'wallet.assets': 'Actifs', 'wallet.activity': 'Activité',
    'common.languagesCount': '7 langues', 'invest.filters': 'Filtres', 'invest.refine': 'Affiner les opportunités', 'invest.matchCount': '{count} produits correspondent', 'invest.reset': 'Réinitialiser', 'invest.riskLevel': 'Niveau de risque', 'invest.allRisk': 'Tous les niveaux', 'invest.low': 'Faible', 'invest.medium': 'Modéré', 'invest.high': 'Élevé', 'invest.availability': 'Disponibilité', 'invest.anyStatus': 'Tous les statuts', 'invest.openNow': 'Disponible maintenant', 'invest.limited': 'Capacité limitée', 'invest.minimum': 'Investissement minimum', 'invest.anyAmount': 'Tout montant', 'invest.showCount': 'Voir {count} opportunités', 'invest.featured': 'Sélection', 'invest.yieldHigh': 'Rendement : décroissant', 'invest.minimumLow': 'Minimum : croissant', 'invest.riskLow': 'Risque : croissant', 'invest.sortTitle': 'Trier les opportunités', 'invest.sortBody': "Choisissez l'ordre adapté à votre analyse", 'invest.featuredBody': 'Ordre sélectionné par la plateforme', 'invest.yieldBody': 'Indicateur prévisionnel ou indicatif', 'invest.minimumBody': 'Commencer par les montants les plus faibles', 'invest.riskBody': 'Afficher d’abord les niveaux de risque faibles', 'invest.closeOptions': 'Fermer les options',
    'profile.title': 'Profil', 'profile.verified': 'Investisseur vérifié', 'profile.identity': 'Identité et KYC', 'profile.security': 'Sécurité et appareils', 'profile.referral': 'Parrainage', 'profile.records': 'Historique des transactions', 'profile.support': "Centre d'aide", 'profile.marketing': 'Préférences marketing', 'profile.official': 'Canaux officiels', 'profile.settings': 'Paramètres', 'profile.signout': 'Se déconnecter de RWA.LAT',
    'auth.hero': 'Actifs mondiaux. Un wallet intelligent.', 'auth.body': 'Investissez en USDT dans le calcul, les actifs réels, les actions et les marchés prédictifs.', 'auth.start': 'Commencer', 'auth.guest': 'Explorer en invité', 'auth.login': 'Bienvenue sur RWA.LAT', 'auth.register': 'Créez votre compte', 'auth.email': 'Continuer par e-mail', 'auth.google': 'Continuer avec Google', 'auth.x': 'Continuer avec X', 'auth.wallet': 'Signer avec le wallet',
    'settings.language': 'Langue', 'settings.notifications': 'Notifications marché', 'settings.marketing': 'Préférences marketing', 'settings.fiat': 'Entrée fiat',
    'marketing.title': 'Préférences marketing', 'marketing.heading': 'Vous décidez de ce que vous recevez.', 'marketing.body': 'Gérez la recherche, les produits et les événements séparément des messages de compte essentiels.', 'marketing.email': 'E-mails recherche et produits', 'marketing.push': 'Push marché et événements', 'marketing.community': 'Invitations communauté', 'marketing.unsubscribe': 'Se désabonner de tout le marketing', 'marketing.saved': 'Préférences marketing Démo enregistrées.',
    'official.title': 'Canaux officiels', 'official.heading': 'Vérifiez avant de faire confiance.', 'official.body': 'RWA.LAT ne demande jamais de phrase de récupération, clé privée, code ni virement vers une adresse personnelle.', 'official.domain': 'Domaine officiel', 'official.social': 'Comptes sociaux vérifiés', 'official.report': 'Signaler une usurpation ou fraude',
    'scam.title': 'Signaler une fraude', 'scam.heading': 'Aidez-nous à enquêter en sécurité.', 'scam.body': 'Envoyez le compte, l’URL ou le wallet suspect. Ne fournissez jamais de phrase de récupération ni de clé privée.', 'scam.source': 'Compte, URL ou wallet suspect', 'scam.details': 'Que s’est-il passé ?', 'scam.submit': 'Créer un signalement Démo', 'guest.badge': 'Invité', 'guest.signin': 'Connectez-vous pour continuer', 'guest.protected': 'Cette action exige un compte sécurisé. Les produits publics restent consultables.', 'profile.trust': 'Confiance et informations',
    'risk.aiTitle': 'Confirmation de décision IA', 'risk.aiBody': 'La sortie IA peut être incomplète ou erronée. Elle ne garantit aucun rendement et ne remplace pas un conseil juridique, fiscal ou réglementé.',
    'trust.title': 'Centre de confiance', 'trust.eyebrow': 'CENTRE DE CONFIANCE', 'trust.heading': "Identifiez l'acteur, le produit et la zone avant d'investir.", 'trust.body': "Consultez au même endroit les règles d'accès, structures, frais, documents juridiques, voies d'assistance et canaux vérifiés.", 'trust.access': 'Accès et régions', 'trust.accessBody': 'Règles invité, contrôles pays et restrictions produit', 'trust.products': 'Informations sur les produits', 'trust.productsBody': 'Émetteur, source du rendement, frais, échéance et sortie', 'trust.legal': 'Centre de documents juridiques', 'trust.legalBody': 'Conditions, confidentialité, risques et versions de consentement', 'trust.supportBody': "Créez et suivez un dossier d'investissement ou de paiement", 'trust.demoNote': "Le contenu Demo sert à examiner le produit. Partenaires, licences, règles d'accès et documents d'offre doivent être approuvés avant toute exécution réelle.",
  },
  pt: {
    'nav.home': 'Início', 'nav.invest': 'Investir', 'nav.portfolio': 'Portfólio', 'nav.wallet': 'Carteira', 'nav.ai': 'Consultor de IA',
    'common.demo': 'Demo', 'common.refresh': 'Atualizar', 'common.viewAll': 'Ver tudo', 'common.back': 'Voltar', 'common.save': 'Salvar preferências', 'common.language': 'Idioma',
    'home.totalPortfolio': 'Portfólio total', 'home.aiScore': 'Pontuação de IA', 'home.marketBrief': 'Resumo de mercado IA', 'home.marketBriefBody': 'A demanda por computação está acelerando.', 'home.explore': 'Explorar oportunidades', 'home.snapshot': 'Visão geral do mercado', 'home.actions': 'Ações de hoje', 'home.income': 'Calendário de rendimentos',
    'invest.title': 'Investir', 'invest.search': 'Buscar oportunidades', 'invest.execution': 'Central de execução', 'invest.noResults': 'Nenhum produto correspondente', 'portfolio.title': 'Portfólio', 'portfolio.total': 'Total investido', 'portfolio.allocation': 'Alocação', 'portfolio.askAi': 'Perguntar à IA', 'wallet.title': 'Carteira', 'wallet.deposit': 'Depositar', 'wallet.withdraw': 'Sacar', 'wallet.transfer': 'Transferir', 'wallet.fiat': 'Fiat em breve', 'wallet.assets': 'Ativos', 'wallet.activity': 'Atividade',
    'common.languagesCount': '7 idiomas', 'invest.filters': 'Filtros', 'invest.refine': 'Refinar oportunidades', 'invest.matchCount': '{count} produtos correspondem', 'invest.reset': 'Redefinir', 'invest.riskLevel': 'Nível de risco', 'invest.allRisk': 'Todos os níveis', 'invest.low': 'Baixo', 'invest.medium': 'Médio', 'invest.high': 'Alto', 'invest.availability': 'Disponibilidade', 'invest.anyStatus': 'Qualquer status', 'invest.openNow': 'Disponível agora', 'invest.limited': 'Capacidade limitada', 'invest.minimum': 'Investimento mínimo', 'invest.anyAmount': 'Qualquer valor', 'invest.showCount': 'Ver {count} oportunidades', 'invest.featured': 'Destaques', 'invest.yieldHigh': 'Retorno: do maior para o menor', 'invest.minimumLow': 'Mínimo: do menor para o maior', 'invest.riskLow': 'Risco: do menor para o maior', 'invest.sortTitle': 'Ordenar oportunidades', 'invest.sortBody': 'Escolha a ordem mais adequada para sua análise', 'invest.featuredBody': 'Ordem selecionada pela plataforma', 'invest.yieldBody': 'Métrica projetada ou indicativa', 'invest.minimumBody': 'Comece pelos valores menores', 'invest.riskBody': 'Veja primeiro as classificações de menor risco', 'invest.closeOptions': 'Fechar opções',
    'profile.title': 'Perfil', 'profile.verified': 'Investidor verificado', 'profile.identity': 'Identidade e KYC', 'profile.security': 'Segurança e dispositivos', 'profile.referral': 'Recompensas', 'profile.records': 'Histórico de transações', 'profile.support': 'Central de suporte', 'profile.marketing': 'Preferências de marketing', 'profile.official': 'Canais oficiais', 'profile.settings': 'Configurações', 'profile.signout': 'Sair da RWA.LAT',
    'auth.hero': 'Ativos globais. Uma carteira inteligente.', 'auth.body': 'Invista com USDT em computação, ativos reais, ações e mercados de previsão.', 'auth.start': 'Começar', 'auth.guest': 'Explorar como visitante', 'auth.login': 'Bem-vindo à RWA.LAT', 'auth.register': 'Crie sua conta', 'auth.email': 'Continuar com e-mail', 'auth.google': 'Continuar com Google', 'auth.x': 'Continuar com X', 'auth.wallet': 'Assinar com carteira',
    'settings.language': 'Idioma', 'settings.notifications': 'Notificações de mercado', 'settings.marketing': 'Preferências de marketing', 'settings.fiat': 'Entrada fiat',
    'marketing.title': 'Preferências de marketing', 'marketing.heading': 'Você decide o que recebe.', 'marketing.body': 'Controle pesquisa, produtos e eventos separadamente das mensagens essenciais da conta.', 'marketing.email': 'E-mail de pesquisa e produtos', 'marketing.push': 'Push de mercado e eventos', 'marketing.community': 'Convites da comunidade', 'marketing.unsubscribe': 'Cancelar todo o marketing', 'marketing.saved': 'Preferências de marketing Demo salvas.',
    'official.title': 'Canais oficiais', 'official.heading': 'Verifique antes de confiar.', 'official.body': 'A RWA.LAT nunca pede frase-semente, chave privada, código ou transferência para endereço pessoal.', 'official.domain': 'Domínio oficial', 'official.social': 'Contas sociais verificadas', 'official.report': 'Denunciar falsificação ou golpe',
    'scam.title': 'Denunciar golpe', 'scam.heading': 'Ajude-nos a investigar com segurança.', 'scam.body': 'Envie a conta, URL ou carteira suspeita. Nunca inclua frase-semente nem chave privada.', 'scam.source': 'Conta, URL ou carteira suspeita', 'scam.details': 'O que aconteceu?', 'scam.submit': 'Criar denúncia Demo', 'guest.badge': 'Visitante', 'guest.signin': 'Entre para continuar', 'guest.protected': 'Esta ação exige uma conta segura. Os produtos públicos continuam disponíveis.', 'profile.trust': 'Confiança e divulgações',
    'risk.aiTitle': 'Confirmação de decisão por IA', 'risk.aiBody': 'A saída da IA pode ser incompleta ou errada. Não garante retorno nem substitui aconselhamento jurídico, fiscal ou licenciado.',
    'trust.title': 'Central de confiança', 'trust.eyebrow': 'CENTRAL DE CONFIANÇA', 'trust.heading': 'Saiba quem, o quê e onde antes de investir.', 'trust.body': 'Consulte em um só lugar regras de acesso, estruturas, taxas, documentos legais, suporte e canais verificados.', 'trust.access': 'Acesso e regiões', 'trust.accessBody': 'Regras de visitante, verificações por país e restrições', 'trust.products': 'Divulgações de produto', 'trust.productsBody': 'Emissor, fonte do retorno, taxas, vencimento e saída', 'trust.legal': 'Central de documentos legais', 'trust.legalBody': 'Termos, privacidade, riscos e versões de consentimento', 'trust.supportBody': 'Crie e acompanhe um caso de investimento ou pagamento', 'trust.demoNote': 'O conteúdo Demo serve para revisar o produto. Parceiros, licenças, regras de acesso e documentos da oferta devem ser aprovados antes de qualquer execução real.',
  },
}

type I18nValue = {
  locale: AppLocale
  direction: 'ltr' | 'rtl'
  setLocale: (locale: AppLocale) => void
  t: (key: TranslationKey, variables?: Record<string, string | number>) => string
}

const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<AppLocale>('en')

  useEffect(() => {
    const stored = window.localStorage.getItem('rwa-language') as AppLocale | null
    const browser = window.navigator.language
    const detected = localeOptions.some((item) => item.code === stored)
      ? stored!
      : browser.startsWith('zh') ? 'zh-CN'
        : localeOptions.find((item) => browser.toLowerCase().startsWith(item.code.toLowerCase()))?.code ?? 'en'
    setLocaleState(detected)
  }, [])

  const setLocale = (next: AppLocale) => {
    setLocaleState(next)
    window.localStorage.setItem('rwa-language', next)
  }
  const direction = localeOptions.find((item) => item.code === locale)?.direction ?? 'ltr'

  useEffect(() => {
    document.documentElement.lang = locale
    document.documentElement.dir = direction
  }, [direction, locale])

  const value = useMemo<I18nValue>(() => ({
    locale,
    direction,
    setLocale,
    t: (key, variables) => {
      const value = dictionaries[locale][key] ?? en[key]
      if (!variables) return value
      return value.replace(/\{(\w+)\}/g, (match, name: string) => variables[name] === undefined ? match : String(variables[name]))
    },
  }), [direction, locale])

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside I18nProvider')
  return value
}
