import type { AppLocale } from './i18n'

type StateContent = { eyebrow: string; title: string; body: string }
type OrderStatusCopy = {
  processing: StateContent; partial: StateContent; failed: StateContent; receipt: StateContent
  orderReceipt: string; orderStatus: string; predictionDescriptor: string; allocationDescriptor: string
  continueFlow: string; returnReview: string; viewPortfolio: string; requestValidated: string; requestValidatedBody: string; done: string
  eligibilityQuote: string; eligibilityQuoteBody: string; checking: string; externalExecution: string; externalExecutionBody: string; locked: string
  filled: string; released: string; noMovement: string; possibleReason: string; reasonBody: string; fundsProtected: string; fundsProtectedBody: string
  demoReference: string; requestedAllocation: string; displayedFee: string; venueId: string; ledgerEntry: string; executionStatus: string
  notCreated: string; demoOnly: string; previewPartial: string; openSupport: string; previewFailed: string
}

const en: OrderStatusCopy = {
  processing: { eyebrow: 'DEMO WORKFLOW ACTIVE', title: 'Your request is being checked.', body: 'The prototype is validating eligibility, quote freshness and available balance. It will not contact an issuer or external venue.' },
  partial: { eyebrow: 'PARTIAL STATE PREVIEW', title: 'Only part of the request was available.', body: '{filled} USDT is represented as filled and the remainder as released. This is a visual state only; no balance changed.' },
  failed: { eyebrow: 'REQUEST NOT RECORDED', title: 'The Demo check could not continue.', body: 'The quote may be stale or an eligibility dependency may be unavailable. No funds were locked and no external order was sent.' },
  receipt: { eyebrow: 'DEMO RECEIPT', title: 'A transparent record of what was simulated.', body: 'This receipt separates interface values from real execution evidence and can be used to review the intended production workflow.' },
  orderReceipt: 'Order receipt', orderStatus: 'Order status', predictionDescriptor: 'Prediction market · read-only distribution Demo', allocationDescriptor: '{category} · prototype allocation', continueFlow: 'Continue Demo workflow', returnReview: 'Return to review', viewPortfolio: 'View Demo portfolio', requestValidated: 'Request validated', requestValidatedBody: 'Amount, disclosure and risk acknowledgement captured', done: 'Done', eligibilityQuote: 'Eligibility and quote check', eligibilityQuoteBody: 'Represented locally for the Demo workflow', checking: 'Checking', externalExecution: 'External execution', externalExecutionBody: 'Disabled until API, ledger and partner gates are active', locked: 'Locked', filled: 'Represented filled', released: 'Represented released', noMovement: 'No external fill, cancellation or balance movement occurred.', possibleReason: 'Possible Demo reason', reasonBody: 'Quote expired before eligibility checks completed.', fundsProtected: 'Funds protected', fundsProtectedBody: 'Available balance remains unchanged because execution is disabled.', demoReference: 'Demo reference', requestedAllocation: 'Requested allocation', displayedFee: 'Displayed fee', venueId: 'External venue ID', ledgerEntry: 'Ledger entry', executionStatus: 'Execution status', notCreated: 'Not created', demoOnly: 'Demo only', previewPartial: 'Preview partial state', openSupport: 'Open support', previewFailed: 'Preview failed state',
}

export const orderStatusCopy: Record<AppLocale, OrderStatusCopy> = {
  en,
  'zh-CN': { processing: { eyebrow: '演示流程进行中', title: '正在检查你的请求。', body: '原型正在校验准入资格、报价有效性与可用余额，不会联系发行方或外部交易场所。' }, partial: { eyebrow: '部分成交状态预览', title: '当前仅有部分额度可用。', body: '界面将 {filled} USDT 模拟为已成交，其余金额模拟为已释放；这仅是视觉状态，余额未发生变化。' }, failed: { eyebrow: '请求未记录', title: '演示检查无法继续。', body: '报价可能已失效，或准入依赖暂不可用。未锁定资金，也未发送外部订单。' }, receipt: { eyebrow: '演示回执', title: '清晰记录本次模拟内容。', body: '回执将界面展示值与真实执行证据明确分开，可用于审阅计划中的生产流程。' }, orderReceipt: '订单回执', orderStatus: '订单状态', predictionDescriptor: '预测市场 · 只读分销演示', allocationDescriptor: '{category} · 原型认购', continueFlow: '继续演示流程', returnReview: '返回订单确认', viewPortfolio: '查看演示组合', requestValidated: '请求已校验', requestValidatedBody: '已记录金额、披露与风险确认', done: '完成', eligibilityQuote: '准入与报价检查', eligibilityQuoteBody: '当前由本地演示流程模拟', checking: '检查中', externalExecution: '外部执行', externalExecutionBody: '接入接口、账本与合作方准入后方可启用', locked: '未启用', filled: '模拟已成交', released: '模拟已释放', noMovement: '没有发生外部成交、撤单或余额变动。', possibleReason: '可能的演示原因', reasonBody: '准入检查完成前报价已过期。', fundsProtected: '资金未受影响', fundsProtectedBody: '执行功能未启用，可用余额保持不变。', demoReference: '演示编号', requestedAllocation: '申请金额', displayedFee: '展示费用', venueId: '外部场所订单号', ledgerEntry: '账本记录', executionStatus: '执行状态', notCreated: '未创建', demoOnly: '仅演示', previewPartial: '预览部分成交状态', openSupport: '打开客服', previewFailed: '预览失败状态' },
  hi: { processing: { eyebrow: 'डेमो प्रक्रिया सक्रिय', title: 'आपके अनुरोध की जाँच हो रही है।', body: 'प्रोटोटाइप पात्रता, कोट और शेष जाँच रहा है। यह जारीकर्ता या बाहरी स्थल से संपर्क नहीं करेगा।' }, partial: { eyebrow: 'आंशिक स्थिति पूर्वावलोकन', title: 'अनुरोध का केवल एक भाग उपलब्ध था।', body: '{filled} USDT को भरा और शेष को जारी दिखाया गया है। यह केवल दृश्य स्थिति है; शेष नहीं बदला।' }, failed: { eyebrow: 'अनुरोध दर्ज नहीं', title: 'डेमो जाँच आगे नहीं बढ़ सकी।', body: 'कोट पुराना या पात्रता सेवा अनुपलब्ध हो सकती है। धन लॉक नहीं हुआ और बाहरी ऑर्डर नहीं भेजा गया।' }, receipt: { eyebrow: 'डेमो रसीद', title: 'सिमुलेशन का पारदर्शी रिकॉर्ड।', body: 'यह रसीद इंटरफ़ेस मान और वास्तविक निष्पादन प्रमाण अलग रखती है।' }, orderReceipt: 'ऑर्डर रसीद', orderStatus: 'ऑर्डर स्थिति', predictionDescriptor: 'प्रेडिक्शन बाज़ार · केवल-पठन डेमो', allocationDescriptor: '{category} · प्रोटोटाइप आवंटन', continueFlow: 'डेमो प्रक्रिया जारी रखें', returnReview: 'समीक्षा पर लौटें', viewPortfolio: 'डेमो पोर्टफोलियो देखें', requestValidated: 'अनुरोध सत्यापित', requestValidatedBody: 'राशि, प्रकटीकरण और जोखिम स्वीकृति दर्ज', done: 'पूर्ण', eligibilityQuote: 'पात्रता और कोट जाँच', eligibilityQuoteBody: 'डेमो के लिए स्थानीय रूप से प्रदर्शित', checking: 'जाँच जारी', externalExecution: 'बाहरी निष्पादन', externalExecutionBody: 'API, लेजर और साझेदार सक्रिय होने तक बंद', locked: 'लॉक', filled: 'दिखाया गया भरा', released: 'दिखाया गया जारी', noMovement: 'कोई बाहरी भराव, रद्दीकरण या शेष परिवर्तन नहीं हुआ।', possibleReason: 'संभावित डेमो कारण', reasonBody: 'पात्रता जाँच पूरी होने से पहले कोट समाप्त हुआ।', fundsProtected: 'धन सुरक्षित', fundsProtectedBody: 'निष्पादन बंद होने से उपलब्ध शेष अपरिवर्तित है।', demoReference: 'डेमो संदर्भ', requestedAllocation: 'अनुरोधित आवंटन', displayedFee: 'दिखाया शुल्क', venueId: 'बाहरी स्थल ID', ledgerEntry: 'लेजर प्रविष्टि', executionStatus: 'निष्पादन स्थिति', notCreated: 'नहीं बनाया', demoOnly: 'केवल डेमो', previewPartial: 'आंशिक स्थिति देखें', openSupport: 'सहायता खोलें', previewFailed: 'विफल स्थिति देखें' },
  es: { processing: { eyebrow: 'FLUJO DEMO ACTIVO', title: 'Estamos comprobando tu solicitud.', body: 'El prototipo valida elegibilidad, vigencia de la cotización y saldo. No contactará a un emisor ni mercado externo.' }, partial: { eyebrow: 'VISTA DE ESTADO PARCIAL', title: 'Solo había disponible una parte.', body: '{filled} USDT se representa como ejecutado y el resto liberado. Es solo una vista; el saldo no cambió.' }, failed: { eyebrow: 'SOLICITUD NO REGISTRADA', title: 'La comprobación Demo no pudo continuar.', body: 'La cotización puede estar vencida o faltar una dependencia. No se bloquearon fondos ni se envió una orden.' }, receipt: { eyebrow: 'RECIBO DEMO', title: 'Registro transparente de la simulación.', body: 'El recibo separa los valores de interfaz de la evidencia real de ejecución.' }, orderReceipt: 'Recibo de orden', orderStatus: 'Estado de orden', predictionDescriptor: 'Mercado predictivo · Demo de solo lectura', allocationDescriptor: '{category} · asignación prototipo', continueFlow: 'Continuar flujo Demo', returnReview: 'Volver a revisar', viewPortfolio: 'Ver cartera Demo', requestValidated: 'Solicitud validada', requestValidatedBody: 'Importe, divulgación y aceptación de riesgo capturados', done: 'Hecho', eligibilityQuote: 'Elegibilidad y cotización', eligibilityQuoteBody: 'Representadas localmente en la Demo', checking: 'Comprobando', externalExecution: 'Ejecución externa', externalExecutionBody: 'Desactivada hasta activar API, registro y socio', locked: 'Bloqueada', filled: 'Ejecución representada', released: 'Liberación representada', noMovement: 'No hubo ejecución, cancelación ni cambio de saldo externo.', possibleReason: 'Posible motivo Demo', reasonBody: 'La cotización venció antes de terminar la elegibilidad.', fundsProtected: 'Fondos protegidos', fundsProtectedBody: 'El saldo no cambia porque la ejecución está desactivada.', demoReference: 'Referencia Demo', requestedAllocation: 'Asignación solicitada', displayedFee: 'Comisión mostrada', venueId: 'ID de mercado externo', ledgerEntry: 'Registro contable', executionStatus: 'Estado de ejecución', notCreated: 'No creado', demoOnly: 'Solo Demo', previewPartial: 'Ver estado parcial', openSupport: 'Abrir soporte', previewFailed: 'Ver estado fallido' },
  ar: { processing: { eyebrow: 'سير العرض نشط', title: 'جارٍ فحص طلبك.', body: 'يفحص النموذج الأهلية وحداثة السعر والرصيد، ولن يتصل بمُصدر أو مكان خارجي.' }, partial: { eyebrow: 'معاينة الحالة الجزئية', title: 'توفر جزء فقط من الطلب.', body: 'يُعرض {filled} USDT كمنفذ والباقي كمحرر. هذه حالة مرئية فقط ولم يتغير الرصيد.' }, failed: { eyebrow: 'لم يُسجل الطلب', title: 'تعذر متابعة الفحص التجريبي.', body: 'قد يكون السعر قديمًا أو خدمة الأهلية غير متاحة. لم تُحجز أموال ولم يُرسل طلب خارجي.' }, receipt: { eyebrow: 'إيصال تجريبي', title: 'سجل شفاف لما تمت محاكاته.', body: 'يفصل الإيصال قيم الواجهة عن دليل التنفيذ الحقيقي لمراجعة سير الإنتاج.' }, orderReceipt: 'إيصال الطلب', orderStatus: 'حالة الطلب', predictionDescriptor: 'سوق توقعات · عرض توزيع للقراءة فقط', allocationDescriptor: '{category} · تخصيص تجريبي', continueFlow: 'متابعة سير العرض', returnReview: 'العودة إلى المراجعة', viewPortfolio: 'عرض المحفظة التجريبية', requestValidated: 'تم التحقق من الطلب', requestValidatedBody: 'تم تسجيل المبلغ والإفصاح وإقرار المخاطر', done: 'تم', eligibilityQuote: 'فحص الأهلية والسعر', eligibilityQuoteBody: 'مُمثل محليًا في سير العرض', checking: 'جارٍ الفحص', externalExecution: 'التنفيذ الخارجي', externalExecutionBody: 'معطل حتى تفعيل الواجهة والسجل والشريك', locked: 'مغلق', filled: 'منفذ تمثيليًا', released: 'محرر تمثيليًا', noMovement: 'لم يحدث تنفيذ أو إلغاء أو تغيير رصيد خارجي.', possibleReason: 'سبب تجريبي محتمل', reasonBody: 'انتهى السعر قبل إكمال فحص الأهلية.', fundsProtected: 'الأموال محمية', fundsProtectedBody: 'يبقى الرصيد دون تغيير لأن التنفيذ معطل.', demoReference: 'مرجع العرض', requestedAllocation: 'التخصيص المطلوب', displayedFee: 'الرسوم المعروضة', venueId: 'معرف المكان الخارجي', ledgerEntry: 'قيد السجل', executionStatus: 'حالة التنفيذ', notCreated: 'لم يُنشأ', demoOnly: 'تجريبي فقط', previewPartial: 'معاينة الحالة الجزئية', openSupport: 'فتح الدعم', previewFailed: 'معاينة حالة الفشل' },
  fr: { processing: { eyebrow: 'FLUX DÉMO ACTIF', title: 'Votre demande est vérifiée.', body: 'Le prototype contrôle éligibilité, fraîcheur de la cotation et solde. Il ne contacte aucun émetteur ni marché externe.' }, partial: { eyebrow: 'APERÇU D’ÉTAT PARTIEL', title: 'Seule une partie était disponible.', body: '{filled} USDT est représenté comme exécuté et le reste libéré. Il s’agit d’un état visuel, sans changement de solde.' }, failed: { eyebrow: 'DEMANDE NON ENREGISTRÉE', title: 'Le contrôle Démo ne peut pas continuer.', body: 'La cotation peut être expirée ou une dépendance indisponible. Aucun fonds bloqué ni ordre externe envoyé.' }, receipt: { eyebrow: 'REÇU DÉMO', title: 'Un relevé transparent de la simulation.', body: 'Ce reçu sépare les valeurs d’interface des preuves d’exécution réelles.' }, orderReceipt: 'Reçu de l’ordre', orderStatus: 'État de l’ordre', predictionDescriptor: 'Marché prédictif · Démo en lecture seule', allocationDescriptor: '{category} · allocation prototype', continueFlow: 'Continuer le flux Démo', returnReview: 'Retour à la vérification', viewPortfolio: 'Voir le portefeuille Démo', requestValidated: 'Demande validée', requestValidatedBody: 'Montant, informations et acceptation du risque enregistrés', done: 'Terminé', eligibilityQuote: 'Éligibilité et cotation', eligibilityQuoteBody: 'Représentées localement dans la Démo', checking: 'Vérification', externalExecution: 'Exécution externe', externalExecutionBody: 'Désactivée jusqu’à activation API, registre et partenaire', locked: 'Verrouillée', filled: 'Exécuté représenté', released: 'Libéré représenté', noMovement: 'Aucune exécution, annulation ou variation de solde externe.', possibleReason: 'Motif Démo possible', reasonBody: 'Cotation expirée avant la fin du contrôle.', fundsProtected: 'Fonds protégés', fundsProtectedBody: 'Le solde reste inchangé car l’exécution est désactivée.', demoReference: 'Référence Démo', requestedAllocation: 'Allocation demandée', displayedFee: 'Frais affichés', venueId: 'ID du marché externe', ledgerEntry: 'Écriture de registre', executionStatus: 'État d’exécution', notCreated: 'Non créé', demoOnly: 'Démo uniquement', previewPartial: 'Aperçu état partiel', openSupport: 'Ouvrir l’assistance', previewFailed: 'Aperçu état d’échec' },
  pt: { processing: { eyebrow: 'FLUXO DEMO ATIVO', title: 'Sua solicitação está sendo verificada.', body: 'O protótipo valida elegibilidade, cotação e saldo. Não entrará em contato com emissor nem mercado externo.' }, partial: { eyebrow: 'PRÉVIA DE ESTADO PARCIAL', title: 'Apenas parte estava disponível.', body: '{filled} USDT é representado como executado e o restante liberado. É apenas visual; o saldo não mudou.' }, failed: { eyebrow: 'SOLICITAÇÃO NÃO REGISTRADA', title: 'A verificação Demo não pôde continuar.', body: 'A cotação pode ter expirado ou faltar uma dependência. Nenhum fundo foi bloqueado nem ordem enviada.' }, receipt: { eyebrow: 'RECIBO DEMO', title: 'Registro transparente da simulação.', body: 'O recibo separa valores da interface de evidências reais de execução.' }, orderReceipt: 'Recibo da ordem', orderStatus: 'Status da ordem', predictionDescriptor: 'Mercado de previsão · Demo somente leitura', allocationDescriptor: '{category} · alocação protótipo', continueFlow: 'Continuar fluxo Demo', returnReview: 'Voltar à revisão', viewPortfolio: 'Ver portfólio Demo', requestValidated: 'Solicitação validada', requestValidatedBody: 'Valor, divulgação e aceite de risco registrados', done: 'Concluído', eligibilityQuote: 'Elegibilidade e cotação', eligibilityQuoteBody: 'Representadas localmente no fluxo Demo', checking: 'Verificando', externalExecution: 'Execução externa', externalExecutionBody: 'Desativada até ativar API, registro e parceiro', locked: 'Bloqueada', filled: 'Execução representada', released: 'Liberação representada', noMovement: 'Não houve execução, cancelamento nem alteração de saldo externo.', possibleReason: 'Possível motivo Demo', reasonBody: 'A cotação expirou antes do fim da elegibilidade.', fundsProtected: 'Fundos protegidos', fundsProtectedBody: 'O saldo permanece igual porque a execução está desativada.', demoReference: 'Referência Demo', requestedAllocation: 'Alocação solicitada', displayedFee: 'Taxa exibida', venueId: 'ID do mercado externo', ledgerEntry: 'Registro contábil', executionStatus: 'Status da execução', notCreated: 'Não criado', demoOnly: 'Somente Demo', previewPartial: 'Ver estado parcial', openSupport: 'Abrir suporte', previewFailed: 'Ver estado de falha' },
}

export function orderStatusText(value: string, variables: Record<string, string | number>) {
  return value.replace(/\{(\w+)\}/g, (match, name: string) => variables[name] === undefined ? match : String(variables[name]))
}
