import type { AppLocale } from './i18n'

type PortfolioDetailCopy = {
  totalUsdt: string; addressCopied: string; copyWallet: string; networkWarning: string
  computePosition: string; computeUnit: string; todayGain: string; dailyRevenue: string; utilization: string; revenueEarned: string
  revenueHistory: string; last30: string; addCapacity: string; capacityBody: string
  aiPlan: string; planLabel: string; planTitle: string; planBody: string; compute: string; rwaIncome: string; globalStocks: string; reserve: string
  gpu: string; cashFlow: string; growth: string; liquidity: string; whyMix: string; whyBody: string; reviewAllocation: string
}

const en: PortfolioDetailCopy = {
  totalUsdt: 'Total USDT', addressCopied: 'Your wallet address was copied.', copyWallet: 'Copy USDT wallet address', networkWarning: 'Use the correct network when depositing.', computePosition: 'Compute position', computeUnit: 'H100 Compute Unit', todayGain: '+12.40 USDT today', dailyRevenue: 'Daily revenue', utilization: 'Utilization', revenueEarned: 'Revenue earned', revenueHistory: 'Revenue history', last30: 'Last 30 days', addCapacity: 'Add compute capacity', capacityBody: 'More capacity, same settlement wallet.', aiPlan: 'AI allocation plan', planLabel: '10,000 USDT plan', planTitle: 'Yield first. Liquid by design.', planBody: 'Generated from your risk score, current exposure and live opportunity data.', compute: 'AI Compute', rwaIncome: 'RWA income', globalStocks: 'Global stocks', reserve: 'USDT reserve', gpu: 'GPU infrastructure', cashFlow: 'Cash-flow assets', growth: 'Growth exposure', liquidity: 'Liquidity buffer', whyMix: 'Why this mix', whyBody: 'Compute demand is improving, RWA income lowers volatility, and USDT reserve protects execution flexibility.', reviewAllocation: 'Review first allocation',
}

export const portfolioDetailCopy: Record<AppLocale, PortfolioDetailCopy> = {
  en,
  'zh-CN': { totalUsdt: 'USDT 总额', addressCopied: '钱包地址已复制。', copyWallet: '复制 USDT 钱包地址', networkWarning: '充值时请务必选择正确网络。', computePosition: '算力持仓', computeUnit: 'H100 算力份额', todayGain: '今日 +12.40 USDT', dailyRevenue: '每日收益', utilization: '利用率', revenueEarned: '累计收益', revenueHistory: '收益历史', last30: '近 30 天', addCapacity: '增加算力份额', capacityBody: '增加份额，继续使用同一结算钱包。', aiPlan: 'AI 资产配置方案', planLabel: '10,000 USDT 配置方案', planTitle: '收益优先，同时保持流动性。', planBody: '根据你的风险评分、当前敞口和实时机会数据生成。', compute: 'AI 算力', rwaIncome: 'RWA 收益资产', globalStocks: '全球股票', reserve: 'USDT 储备', gpu: 'GPU 基础设施', cashFlow: '现金流资产', growth: '成长型敞口', liquidity: '流动性缓冲', whyMix: '为何这样配置', whyBody: '算力需求正在改善，RWA 收益有助于降低波动，USDT 储备则保留执行弹性。', reviewAllocation: '查看首笔配置' },
  hi: { totalUsdt: 'कुल USDT', addressCopied: 'वॉलेट पता कॉपी हुआ।', copyWallet: 'USDT वॉलेट पता कॉपी करें', networkWarning: 'जमा करते समय सही नेटवर्क चुनें।', computePosition: 'कंप्यूट स्थिति', computeUnit: 'H100 कंप्यूट इकाई', todayGain: 'आज +12.40 USDT', dailyRevenue: 'दैनिक आय', utilization: 'उपयोग', revenueEarned: 'अर्जित आय', revenueHistory: 'आय इतिहास', last30: 'पिछले 30 दिन', addCapacity: 'कंप्यूट क्षमता जोड़ें', capacityBody: 'अधिक क्षमता, वही निपटान वॉलेट।', aiPlan: 'AI आवंटन योजना', planLabel: '10,000 USDT योजना', planTitle: 'प्रतिफल पहले, तरलता के साथ।', planBody: 'आपके जोखिम स्कोर, मौजूदा एक्सपोज़र और लाइव अवसरों से तैयार।', compute: 'AI कंप्यूट', rwaIncome: 'RWA आय', globalStocks: 'वैश्विक शेयर', reserve: 'USDT आरक्षित', gpu: 'GPU अवसंरचना', cashFlow: 'नकदी-प्रवाह परिसंपत्तियाँ', growth: 'वृद्धि एक्सपोज़र', liquidity: 'तरलता बफर', whyMix: 'यह मिश्रण क्यों', whyBody: 'कंप्यूट मांग सुधर रही है, RWA आय अस्थिरता घटाती है और USDT आरक्षित लचीलापन रखता है।', reviewAllocation: 'पहले आवंटन की समीक्षा' },
  es: { totalUsdt: 'USDT total', addressCopied: 'Dirección de billetera copiada.', copyWallet: 'Copiar dirección USDT', networkWarning: 'Usa la red correcta al depositar.', computePosition: 'Posición de cómputo', computeUnit: 'Unidad de cómputo H100', todayGain: '+12,40 USDT hoy', dailyRevenue: 'Ingreso diario', utilization: 'Utilización', revenueEarned: 'Ingreso acumulado', revenueHistory: 'Historial de ingresos', last30: 'Últimos 30 días', addCapacity: 'Añadir capacidad', capacityBody: 'Más capacidad, la misma billetera de liquidación.', aiPlan: 'Plan de asignación IA', planLabel: 'Plan de 10.000 USDT', planTitle: 'Rendimiento primero, con liquidez.', planBody: 'Generado a partir de tu riesgo, exposición y oportunidades en vivo.', compute: 'Cómputo IA', rwaIncome: 'Ingresos RWA', globalStocks: 'Acciones globales', reserve: 'Reserva USDT', gpu: 'Infraestructura GPU', cashFlow: 'Activos con flujo de caja', growth: 'Exposición de crecimiento', liquidity: 'Reserva de liquidez', whyMix: 'Por qué esta combinación', whyBody: 'Mejora la demanda de cómputo, RWA reduce volatilidad y USDT conserva flexibilidad.', reviewAllocation: 'Revisar primera asignación' },
  ar: { totalUsdt: 'إجمالي USDT', addressCopied: 'تم نسخ عنوان المحفظة.', copyWallet: 'نسخ عنوان محفظة USDT', networkWarning: 'استخدم الشبكة الصحيحة عند الإيداع.', computePosition: 'مركز الحوسبة', computeUnit: 'وحدة حوسبة H100', todayGain: '+12.40 USDT اليوم', dailyRevenue: 'الإيراد اليومي', utilization: 'الاستخدام', revenueEarned: 'الإيراد المكتسب', revenueHistory: 'سجل الإيرادات', last30: 'آخر 30 يومًا', addCapacity: 'إضافة سعة حوسبة', capacityBody: 'سعة أكبر، ومحفظة التسوية نفسها.', aiPlan: 'خطة تخصيص بالذكاء الاصطناعي', planLabel: 'خطة 10,000 USDT', planTitle: 'العائد أولًا مع الحفاظ على السيولة.', planBody: 'مولدة من تقييم مخاطر محفظتك والتعرض الحالي والفرص المباشرة.', compute: 'حوسبة الذكاء الاصطناعي', rwaIncome: 'دخل RWA', globalStocks: 'أسهم عالمية', reserve: 'احتياطي USDT', gpu: 'بنية GPU', cashFlow: 'أصول التدفق النقدي', growth: 'تعرض النمو', liquidity: 'هامش السيولة', whyMix: 'لماذا هذا المزيج', whyBody: 'يتحسن طلب الحوسبة، ويقلل دخل RWA التقلب، ويحفظ احتياطي USDT مرونة التنفيذ.', reviewAllocation: 'مراجعة أول تخصيص' },
  fr: { totalUsdt: 'Total USDT', addressCopied: 'Adresse du wallet copiée.', copyWallet: 'Copier l’adresse USDT', networkWarning: 'Utilisez le bon réseau pour le dépôt.', computePosition: 'Position de calcul', computeUnit: 'Unité de calcul H100', todayGain: '+12,40 USDT aujourd’hui', dailyRevenue: 'Revenu quotidien', utilization: 'Utilisation', revenueEarned: 'Revenu cumulé', revenueHistory: 'Historique des revenus', last30: '30 derniers jours', addCapacity: 'Ajouter de la capacité', capacityBody: 'Plus de capacité, même wallet de règlement.', aiPlan: 'Plan d’allocation IA', planLabel: 'Plan de 10 000 USDT', planTitle: 'Le rendement d’abord, avec de la liquidité.', planBody: 'Généré à partir de votre risque, exposition et des opportunités en direct.', compute: 'Calcul IA', rwaIncome: 'Revenus RWA', globalStocks: 'Actions mondiales', reserve: 'Réserve USDT', gpu: 'Infrastructure GPU', cashFlow: 'Actifs de trésorerie', growth: 'Exposition croissance', liquidity: 'Réserve de liquidité', whyMix: 'Pourquoi cette combinaison', whyBody: 'La demande de calcul progresse, le revenu RWA réduit la volatilité et la réserve USDT préserve la flexibilité.', reviewAllocation: 'Examiner la première allocation' },
  pt: { totalUsdt: 'USDT total', addressCopied: 'Endereço da carteira copiado.', copyWallet: 'Copiar endereço USDT', networkWarning: 'Use a rede correta ao depositar.', computePosition: 'Posição de computação', computeUnit: 'Unidade de computação H100', todayGain: '+12,40 USDT hoje', dailyRevenue: 'Receita diária', utilization: 'Utilização', revenueEarned: 'Receita acumulada', revenueHistory: 'Histórico de receita', last30: 'Últimos 30 dias', addCapacity: 'Adicionar capacidade', capacityBody: 'Mais capacidade, a mesma carteira de liquidação.', aiPlan: 'Plano de alocação por IA', planLabel: 'Plano de 10.000 USDT', planTitle: 'Retorno primeiro, com liquidez.', planBody: 'Gerado a partir do seu risco, exposição e oportunidades ao vivo.', compute: 'Computação de IA', rwaIncome: 'Renda RWA', globalStocks: 'Ações globais', reserve: 'Reserva USDT', gpu: 'Infraestrutura GPU', cashFlow: 'Ativos de fluxo de caixa', growth: 'Exposição de crescimento', liquidity: 'Reserva de liquidez', whyMix: 'Por que esta combinação', whyBody: 'A demanda por computação melhora, a renda RWA reduz volatilidade e a reserva USDT preserva flexibilidade.', reviewAllocation: 'Revisar primeira alocação' },
}
