import type { AppLocale } from './i18n'

type ScreenCopy = {
  home: {
    publicPreview: string; exploreGlobalAssets: string; liveDiscovery: string; signInPortfolio: string; today: string
    networkAnimation: string; realEstate: string; privateCredit: string; aiCompute: string; tokenizedTreasuries: string
    snapshotAria: string; computeDemand: string; utilization: string; rwaIncome: string; supportedSettlement: string; availableToDeploy: string
    tasksAria: string; reviewedCount: string; concentrationTitle: string; concentrationBody: string; openPlan: string
    addressTitle: string; addressBody: string; reviewAccess: string; reviewed: string; incomeAria: string; incomeBody: string
    curated: string; featuredAria: string; recentActivity: string; activityAria: string; viewLedger: string
    computeRevenue: string; rwaSettled: string; marketRefreshed: string
  }
  invest: {
    clearSearch: string; balance: string; openCapacity: string; assetCount: string; settled: string; aiSignal: string; positive: string; computeLeads: string
    categoriesAria: string; all: string; compute: string; rwa: string; stocks: string; prediction: string
    computeTitle: string; projectedApy: string; from: string; noResultsBody: string; resetCatalogue: string
    usdtRouting: string; routingBody: string; preTrade: string; preTradeBody: string
  }
  prediction: {
    aria: string; desk: string; refreshing: string; live: string; loading: string; fallback: string; updated: string; discoveryApi: string
    openMarket: string; yes: string; unavailable: string; disclosure: string
  }
}

const en: ScreenCopy = {
  home: {
    publicPreview: 'PUBLIC MARKET PREVIEW', exploreGlobalAssets: 'Explore global assets', liveDiscovery: 'Live discovery · Demo execution', signInPortfolio: 'Sign in to view a personal portfolio', today: 'today',
    networkAnimation: 'Animated global investment network', realEstate: 'Real Estate', privateCredit: 'Private Credit', aiCompute: 'AI Compute', tokenizedTreasuries: 'Tokenized Treasuries',
    snapshotAria: 'Market snapshot', computeDemand: 'Compute demand', utilization: '+3.4% utilization', rwaIncome: 'RWA income', supportedSettlement: 'Supported settlement', availableToDeploy: 'Available to deploy',
    tasksAria: "Today's investor tasks", reviewedCount: '{count}/2 reviewed', concentrationTitle: 'Review concentration signal', concentrationBody: 'AI leaders basket is 4% above your preferred technology allocation.', openPlan: 'Open plan',
    addressTitle: 'Refresh investor address', addressBody: 'Address confirmation is due before the next RWA allocation window.', reviewAccess: 'Review access', reviewed: 'Reviewed', incomeAria: 'Income calendar', incomeBody: 'Estimated monthly operating distribution · Demo',
    curated: 'Curated for your profile', featuredAria: 'Featured projects', recentActivity: 'Recent activity', activityAria: 'Recent activity', viewLedger: 'View ledger',
    computeRevenue: 'Compute revenue accrued', rwaSettled: 'RWA allocation settled', marketRefreshed: 'Market snapshot refreshed with Demo data.',
  },
  invest: {
    clearSearch: 'Clear search', balance: 'USDT balance', openCapacity: 'Open capacity', assetCount: '4 assets', settled: 'USDT settled', aiSignal: 'AI signal', positive: 'Positive', computeLeads: 'Compute leads',
    categoriesAria: 'Investment categories', all: 'All', compute: 'Compute', rwa: 'RWA', stocks: 'Stocks', prediction: 'Prediction',
    computeTitle: 'AI Compute Infrastructure', projectedApy: 'projected APY', from: 'From', noResultsBody: 'Try a different keyword or remove the active filter.', resetCatalogue: 'Reset catalogue',
    usdtRouting: 'USDT routing', routingBody: 'TRON, Ethereum and Arbitrum balances are ready for allocation.', preTrade: 'AI pre-trade check', preTradeBody: 'Review concentration, liquidity and product risk before investing.',
  },
  prediction: {
    aria: 'Polymarket prediction market desk', desk: 'Polymarket desk', refreshing: 'Refreshing', live: 'Live public market data', loading: 'Loading public market data', fallback: 'Demo fallback data', updated: 'Updated {time}', discoveryApi: 'Gamma discovery API', openMarket: 'Open market', yes: 'Yes', unavailable: 'Polymarket feed unavailable. Showing demo markets.',
    disclosure: 'Market discovery data is sourced from Polymarket Gamma when available. RWA.LAT execution remains Demo until distribution access, user eligibility and regional controls are configured.',
  },
}

export const screenCopy: Record<AppLocale, ScreenCopy> = {
  en,
  'zh-CN': {
    home: {
      publicPreview: '公开市场预览', exploreGlobalAssets: '探索全球资产', liveDiscovery: '实时发现 · 演示执行', signInPortfolio: '登录后查看个人资产组合', today: '今日',
      networkAnimation: '全球投资网络动态视图', realEstate: '房地产', privateCredit: '私募信贷', aiCompute: 'AI 算力', tokenizedTreasuries: '代币化国债',
      snapshotAria: '市场概览', computeDemand: '算力需求', utilization: '利用率 +3.4%', rwaIncome: 'RWA 收益', supportedSettlement: '支持的结算资产', availableToDeploy: '可投资余额',
      tasksAria: '今日投资事项', reviewedCount: '已查看 {count}/2', concentrationTitle: '检查持仓集中度信号', concentrationBody: 'AI 龙头组合较你的科技行业目标配置高出 4%。', openPlan: '查看方案',
      addressTitle: '更新投资者地址', addressBody: '下一个 RWA 认购窗口前需完成地址确认。', reviewAccess: '检查准入', reviewed: '已查看', incomeAria: '收益日历', incomeBody: '预计月度经营收益分配 · 演示',
      curated: '为你的偏好精选', featuredAria: '精选项目', recentActivity: '最近动态', activityAria: '最近动态', viewLedger: '查看流水',
      computeRevenue: '算力收益已计提', rwaSettled: 'RWA 认购已结算', marketRefreshed: '市场概览已使用演示数据刷新。',
    },
    invest: {
      clearSearch: '清除搜索', balance: 'USDT 余额', openCapacity: '开放额度', assetCount: '4 项资产', settled: 'USDT 结算', aiSignal: 'AI 信号', positive: '积极', computeLeads: '算力领先',
      categoriesAria: '投资类别', all: '全部', compute: '算力', rwa: 'RWA', stocks: '美股', prediction: '预测市场',
      computeTitle: 'AI 算力基础设施', projectedApy: '预计年化收益率', from: '起投', noResultsBody: '请更换关键词，或移除当前筛选条件。', resetCatalogue: '重置产品目录',
      usdtRouting: 'USDT 路由', routingBody: 'TRON、Ethereum 与 Arbitrum 余额均可用于配置。', preTrade: 'AI 交易前检查', preTradeBody: '投资前检查集中度、流动性与产品风险。',
    },
    prediction: {
      aria: 'Polymarket 预测市场中心', desk: 'Polymarket 市场', refreshing: '刷新中', live: '实时公开市场数据', loading: '正在加载公开市场数据', fallback: '演示备用数据', updated: '更新于 {time}', discoveryApi: 'Gamma 市场发现接口', openMarket: '开放市场', yes: '是', unavailable: 'Polymarket 数据暂不可用，现显示演示市场。',
      disclosure: '市场发现数据在可用时来自 Polymarket Gamma。RWA.LAT 的执行功能仍为演示，待分销权限、用户准入与地区控制配置完成后方可启用。',
    },
  },
  hi: {
    home: {
      publicPreview: 'सार्वजनिक बाज़ार पूर्वावलोकन', exploreGlobalAssets: 'वैश्विक परिसंपत्तियाँ खोजें', liveDiscovery: 'लाइव खोज · डेमो निष्पादन', signInPortfolio: 'अपना पोर्टफोलियो देखने के लिए साइन इन करें', today: 'आज',
      networkAnimation: 'वैश्विक निवेश नेटवर्क का एनिमेटेड दृश्य', realEstate: 'रियल एस्टेट', privateCredit: 'निजी ऋण', aiCompute: 'AI कंप्यूट', tokenizedTreasuries: 'टोकनाइज़्ड ट्रेज़री',
      snapshotAria: 'बाज़ार स्नैपशॉट', computeDemand: 'कंप्यूट मांग', utilization: 'उपयोग +3.4%', rwaIncome: 'RWA आय', supportedSettlement: 'समर्थित निपटान', availableToDeploy: 'निवेश के लिए उपलब्ध',
      tasksAria: 'आज के निवेश कार्य', reviewedCount: '{count}/2 की समीक्षा', concentrationTitle: 'एकाग्रता संकेत की समीक्षा करें', concentrationBody: 'AI लीडर्स बास्केट आपके पसंदीदा तकनीकी आवंटन से 4% अधिक है।', openPlan: 'योजना खोलें',
      addressTitle: 'निवेशक पता अपडेट करें', addressBody: 'अगली RWA आवंटन विंडो से पहले पते की पुष्टि आवश्यक है।', reviewAccess: 'पात्रता देखें', reviewed: 'समीक्षित', incomeAria: 'आय कैलेंडर', incomeBody: 'अनुमानित मासिक परिचालन वितरण · डेमो',
      curated: 'आपके प्रोफ़ाइल के लिए चुना गया', featuredAria: 'चुनिंदा परियोजनाएँ', recentActivity: 'हाल की गतिविधि', activityAria: 'हाल की गतिविधि', viewLedger: 'लेजर देखें', computeRevenue: 'कंप्यूट आय अर्जित', rwaSettled: 'RWA आवंटन निपटाया गया', marketRefreshed: 'बाज़ार स्नैपशॉट डेमो डेटा से अपडेट हुआ।',
    },
    invest: {
      clearSearch: 'खोज साफ़ करें', balance: 'USDT शेष', openCapacity: 'उपलब्ध क्षमता', assetCount: '4 परिसंपत्तियाँ', settled: 'USDT निपटान', aiSignal: 'AI संकेत', positive: 'सकारात्मक', computeLeads: 'कंप्यूट अग्रणी', categoriesAria: 'निवेश श्रेणियाँ', all: 'सभी', compute: 'कंप्यूट', rwa: 'RWA', stocks: 'शेयर', prediction: 'पूर्वानुमान', computeTitle: 'AI कंप्यूट अवसंरचना', projectedApy: 'अनुमानित APY', from: 'न्यूनतम', noResultsBody: 'दूसरा कीवर्ड आज़माएँ या सक्रिय फ़िल्टर हटाएँ।', resetCatalogue: 'कैटलॉग रीसेट करें', usdtRouting: 'USDT रूटिंग', routingBody: 'TRON, Ethereum और Arbitrum शेष आवंटन के लिए तैयार हैं।', preTrade: 'AI पूर्व-व्यापार जाँच', preTradeBody: 'निवेश से पहले एकाग्रता, तरलता और उत्पाद जोखिम की समीक्षा करें।',
    },
    prediction: {
      aria: 'Polymarket पूर्वानुमान बाज़ार डेस्क', desk: 'Polymarket डेस्क', refreshing: 'रीफ़्रेश हो रहा है', live: 'लाइव सार्वजनिक बाज़ार डेटा', loading: 'सार्वजनिक बाज़ार डेटा लोड हो रहा है', fallback: 'डेमो बैकअप डेटा', updated: '{time} पर अपडेट', discoveryApi: 'Gamma खोज API', openMarket: 'खुला बाज़ार', yes: 'हाँ', unavailable: 'Polymarket फ़ीड उपलब्ध नहीं है। डेमो बाज़ार दिखाए जा रहे हैं।', disclosure: 'उपलब्ध होने पर बाज़ार खोज डेटा Polymarket Gamma से लिया जाता है। वितरण पहुँच, उपयोगकर्ता पात्रता और क्षेत्रीय नियंत्रण कॉन्फ़िगर होने तक RWA.LAT निष्पादन डेमो रहेगा।',
    },
  },
  es: {
    home: {
      publicPreview: 'VISTA PÚBLICA DEL MERCADO', exploreGlobalAssets: 'Explora activos globales', liveDiscovery: 'Descubrimiento en vivo · Ejecución demo', signInPortfolio: 'Inicia sesión para ver tu cartera', today: 'hoy', networkAnimation: 'Red global de inversión animada', realEstate: 'Inmobiliario', privateCredit: 'Crédito privado', aiCompute: 'Cómputo IA', tokenizedTreasuries: 'Bonos del Tesoro tokenizados', snapshotAria: 'Resumen del mercado', computeDemand: 'Demanda de cómputo', utilization: 'utilización +3,4 %', rwaIncome: 'Ingresos RWA', supportedSettlement: 'Liquidación admitida', availableToDeploy: 'Disponible para invertir', tasksAria: 'Tareas de inversión de hoy', reviewedCount: '{count}/2 revisadas', concentrationTitle: 'Revisar señal de concentración', concentrationBody: 'La cesta de líderes de IA supera en un 4 % tu asignación tecnológica preferida.', openPlan: 'Abrir plan', addressTitle: 'Actualizar domicilio del inversor', addressBody: 'Debes confirmar el domicilio antes de la próxima ventana RWA.', reviewAccess: 'Revisar acceso', reviewed: 'Revisado', incomeAria: 'Calendario de ingresos', incomeBody: 'Distribución operativa mensual estimada · Demo', curated: 'Selección para tu perfil', featuredAria: 'Proyectos destacados', recentActivity: 'Actividad reciente', activityAria: 'Actividad reciente', viewLedger: 'Ver movimientos', computeRevenue: 'Ingreso de cómputo devengado', rwaSettled: 'Asignación RWA liquidada', marketRefreshed: 'Resumen actualizado con datos demo.',
    },
    invest: {
      clearSearch: 'Borrar búsqueda', balance: 'Saldo USDT', openCapacity: 'Capacidad disponible', assetCount: '4 activos', settled: 'Liquidación en USDT', aiSignal: 'Señal IA', positive: 'Positiva', computeLeads: 'Lidera cómputo', categoriesAria: 'Categorías de inversión', all: 'Todo', compute: 'Cómputo', rwa: 'RWA', stocks: 'Acciones', prediction: 'Predicción', computeTitle: 'Infraestructura de cómputo IA', projectedApy: 'APY proyectado', from: 'Desde', noResultsBody: 'Prueba otra palabra o elimina el filtro activo.', resetCatalogue: 'Restablecer catálogo', usdtRouting: 'Ruta USDT', routingBody: 'Los saldos de TRON, Ethereum y Arbitrum están listos para asignarse.', preTrade: 'Control previo de IA', preTradeBody: 'Revisa concentración, liquidez y riesgo antes de invertir.',
    },
    prediction: {
      aria: 'Mesa de mercados predictivos de Polymarket', desk: 'Mesa Polymarket', refreshing: 'Actualizando', live: 'Datos públicos en vivo', loading: 'Cargando datos públicos', fallback: 'Datos demo de respaldo', updated: 'Actualizado {time}', discoveryApi: 'API de descubrimiento Gamma', openMarket: 'Mercado abierto', yes: 'Sí', unavailable: 'El feed de Polymarket no está disponible. Se muestran mercados demo.', disclosure: 'Los datos de descubrimiento proceden de Polymarket Gamma cuando están disponibles. La ejecución de RWA.LAT seguirá siendo demo hasta configurar la distribución, la elegibilidad y los controles regionales.',
    },
  },
  ar: {
    home: {
      publicPreview: 'معاينة السوق العامة', exploreGlobalAssets: 'استكشف الأصول العالمية', liveDiscovery: 'اكتشاف مباشر · تنفيذ تجريبي', signInPortfolio: 'سجّل الدخول لعرض محفظتك', today: 'اليوم', networkAnimation: 'عرض متحرك لشبكة الاستثمار العالمية', realEstate: 'العقارات', privateCredit: 'الائتمان الخاص', aiCompute: 'حوسبة الذكاء الاصطناعي', tokenizedTreasuries: 'سندات خزانة مرمّزة', snapshotAria: 'ملخص السوق', computeDemand: 'طلب الحوسبة', utilization: 'الاستخدام +3.4%', rwaIncome: 'دخل RWA', supportedSettlement: 'التسوية المدعومة', availableToDeploy: 'متاح للاستثمار', tasksAria: 'مهام الاستثمار اليوم', reviewedCount: 'تمت مراجعة {count}/2', concentrationTitle: 'راجع إشارة التركّز', concentrationBody: 'سلة رواد الذكاء الاصطناعي أعلى بنسبة 4% من تخصيصك التقني المفضّل.', openPlan: 'فتح الخطة', addressTitle: 'تحديث عنوان المستثمر', addressBody: 'يلزم تأكيد العنوان قبل نافذة تخصيص RWA التالية.', reviewAccess: 'مراجعة الأهلية', reviewed: 'تمت المراجعة', incomeAria: 'تقويم الدخل', incomeBody: 'توزيع تشغيلي شهري تقديري · تجريبي', curated: 'مختار لملفك', featuredAria: 'مشروعات مختارة', recentActivity: 'النشاط الأخير', activityAria: 'النشاط الأخير', viewLedger: 'عرض السجل', computeRevenue: 'تم استحقاق إيراد الحوسبة', rwaSettled: 'تمت تسوية تخصيص RWA', marketRefreshed: 'تم تحديث ملخص السوق ببيانات تجريبية.',
    },
    invest: {
      clearSearch: 'مسح البحث', balance: 'رصيد USDT', openCapacity: 'السعة المتاحة', assetCount: '4 أصول', settled: 'تسوية USDT', aiSignal: 'إشارة الذكاء الاصطناعي', positive: 'إيجابية', computeLeads: 'الحوسبة تتصدر', categoriesAria: 'فئات الاستثمار', all: 'الكل', compute: 'الحوسبة', rwa: 'RWA', stocks: 'الأسهم', prediction: 'التوقعات', computeTitle: 'بنية حوسبة الذكاء الاصطناعي', projectedApy: 'عائد سنوي متوقع', from: 'ابتداءً من', noResultsBody: 'جرّب كلمة أخرى أو أزل عامل التصفية النشط.', resetCatalogue: 'إعادة ضبط القائمة', usdtRouting: 'توجيه USDT', routingBody: 'أرصدة TRON وEthereum وArbitrum جاهزة للتخصيص.', preTrade: 'فحص الذكاء الاصطناعي قبل التداول', preTradeBody: 'راجع التركّز والسيولة ومخاطر المنتج قبل الاستثمار.',
    },
    prediction: {
      aria: 'منصة أسواق التوقعات Polymarket', desk: 'منصة Polymarket', refreshing: 'جارٍ التحديث', live: 'بيانات سوق عامة مباشرة', loading: 'جارٍ تحميل بيانات السوق', fallback: 'بيانات تجريبية احتياطية', updated: 'تم التحديث {time}', discoveryApi: 'واجهة اكتشاف Gamma', openMarket: 'سوق مفتوح', yes: 'نعم', unavailable: 'تعذر الوصول إلى Polymarket. يتم عرض أسواق تجريبية.', disclosure: 'تأتي بيانات اكتشاف الأسواق من Polymarket Gamma عند توفرها. يظل التنفيذ في RWA.LAT تجريبيًا إلى أن تُضبط صلاحيات التوزيع وأهلية المستخدم والضوابط الإقليمية.',
    },
  },
  fr: {
    home: {
      publicPreview: 'APERÇU PUBLIC DES MARCHÉS', exploreGlobalAssets: 'Explorez les actifs mondiaux', liveDiscovery: 'Découverte en direct · Exécution démo', signInPortfolio: 'Connectez-vous pour voir votre portefeuille', today: "aujourd’hui", networkAnimation: "Vue animée du réseau mondial d’investissement", realEstate: 'Immobilier', privateCredit: 'Crédit privé', aiCompute: 'Calcul IA', tokenizedTreasuries: 'Bons du Trésor tokenisés', snapshotAria: 'Aperçu du marché', computeDemand: 'Demande de calcul', utilization: 'utilisation +3,4 %', rwaIncome: 'Revenus RWA', supportedSettlement: 'Règlement pris en charge', availableToDeploy: 'Disponible à investir', tasksAria: "Tâches d’investissement du jour", reviewedCount: '{count}/2 examinées', concentrationTitle: 'Examiner le signal de concentration', concentrationBody: "Le panier des leaders IA dépasse de 4 % votre allocation technologique cible.", openPlan: 'Ouvrir le plan', addressTitle: "Actualiser l’adresse investisseur", addressBody: "La confirmation est requise avant la prochaine fenêtre d’allocation RWA.", reviewAccess: "Vérifier l’accès", reviewed: 'Examiné', incomeAria: 'Calendrier des revenus', incomeBody: 'Distribution opérationnelle mensuelle estimée · Démo', curated: 'Sélection adaptée à votre profil', featuredAria: 'Projets sélectionnés', recentActivity: 'Activité récente', activityAria: 'Activité récente', viewLedger: 'Voir le registre', computeRevenue: 'Revenu de calcul comptabilisé', rwaSettled: 'Allocation RWA réglée', marketRefreshed: 'Aperçu actualisé avec les données démo.',
    },
    invest: {
      clearSearch: 'Effacer la recherche', balance: 'Solde USDT', openCapacity: 'Capacité disponible', assetCount: '4 actifs', settled: 'Règlement en USDT', aiSignal: 'Signal IA', positive: 'Positif', computeLeads: 'Le calcul domine', categoriesAria: "Catégories d’investissement", all: 'Tout', compute: 'Calcul', rwa: 'RWA', stocks: 'Actions', prediction: 'Prédiction', computeTitle: 'Infrastructure de calcul IA', projectedApy: 'APY projeté', from: 'À partir de', noResultsBody: 'Essayez un autre mot-clé ou retirez le filtre actif.', resetCatalogue: 'Réinitialiser le catalogue', usdtRouting: 'Routage USDT', routingBody: 'Les soldes TRON, Ethereum et Arbitrum sont prêts à être alloués.', preTrade: 'Contrôle IA avant transaction', preTradeBody: 'Examinez concentration, liquidité et risque produit avant d’investir.',
    },
    prediction: {
      aria: 'Marchés prédictifs Polymarket', desk: 'Espace Polymarket', refreshing: 'Actualisation', live: 'Données publiques en direct', loading: 'Chargement des données publiques', fallback: 'Données démo de secours', updated: 'Actualisé à {time}', discoveryApi: 'API de découverte Gamma', openMarket: 'Marché ouvert', yes: 'Oui', unavailable: 'Le flux Polymarket est indisponible. Affichage des marchés démo.', disclosure: "Les données de découverte proviennent de Polymarket Gamma lorsqu’elles sont disponibles. L’exécution RWA.LAT reste en mode démo jusqu’à la configuration de la distribution, de l’éligibilité et des contrôles régionaux.",
    },
  },
  pt: {
    home: {
      publicPreview: 'PRÉVIA PÚBLICA DO MERCADO', exploreGlobalAssets: 'Explore ativos globais', liveDiscovery: 'Descoberta ao vivo · Execução demo', signInPortfolio: 'Entre para ver seu portfólio', today: 'hoje', networkAnimation: 'Visualização animada da rede global de investimentos', realEstate: 'Imóveis', privateCredit: 'Crédito privado', aiCompute: 'Computação de IA', tokenizedTreasuries: 'Títulos do Tesouro tokenizados', snapshotAria: 'Resumo do mercado', computeDemand: 'Demanda de computação', utilization: 'utilização +3,4%', rwaIncome: 'Renda RWA', supportedSettlement: 'Liquidação compatível', availableToDeploy: 'Disponível para investir', tasksAria: 'Tarefas de investimento de hoje', reviewedCount: '{count}/2 revisadas', concentrationTitle: 'Revisar sinal de concentração', concentrationBody: 'A cesta de líderes de IA está 4% acima da sua alocação tecnológica preferida.', openPlan: 'Abrir plano', addressTitle: 'Atualizar endereço do investidor', addressBody: 'A confirmação do endereço é necessária antes da próxima janela RWA.', reviewAccess: 'Revisar acesso', reviewed: 'Revisado', incomeAria: 'Calendário de renda', incomeBody: 'Distribuição operacional mensal estimada · Demo', curated: 'Selecionado para seu perfil', featuredAria: 'Projetos em destaque', recentActivity: 'Atividade recente', activityAria: 'Atividade recente', viewLedger: 'Ver extrato', computeRevenue: 'Receita de computação acumulada', rwaSettled: 'Alocação RWA liquidada', marketRefreshed: 'Resumo atualizado com dados demo.',
    },
    invest: {
      clearSearch: 'Limpar busca', balance: 'Saldo USDT', openCapacity: 'Capacidade disponível', assetCount: '4 ativos', settled: 'Liquidação em USDT', aiSignal: 'Sinal de IA', positive: 'Positivo', computeLeads: 'Computação lidera', categoriesAria: 'Categorias de investimento', all: 'Todos', compute: 'Computação', rwa: 'RWA', stocks: 'Ações', prediction: 'Previsão', computeTitle: 'Infraestrutura de computação de IA', projectedApy: 'APY projetado', from: 'A partir de', noResultsBody: 'Tente outra palavra ou remova o filtro ativo.', resetCatalogue: 'Redefinir catálogo', usdtRouting: 'Roteamento USDT', routingBody: 'Os saldos TRON, Ethereum e Arbitrum estão prontos para alocação.', preTrade: 'Verificação de IA antes da ordem', preTradeBody: 'Revise concentração, liquidez e risco antes de investir.',
    },
    prediction: {
      aria: 'Mesa de mercados preditivos Polymarket', desk: 'Mesa Polymarket', refreshing: 'Atualizando', live: 'Dados públicos ao vivo', loading: 'Carregando dados públicos', fallback: 'Dados demo de contingência', updated: 'Atualizado {time}', discoveryApi: 'API de descoberta Gamma', openMarket: 'Mercado aberto', yes: 'Sim', unavailable: 'O feed da Polymarket está indisponível. Exibindo mercados demo.', disclosure: 'Os dados de descoberta vêm da Polymarket Gamma quando disponíveis. A execução da RWA.LAT continuará demo até a configuração da distribuição, elegibilidade e controles regionais.',
    },
  },
}

export function interpolateCopy(value: string, variables: Record<string, string | number>) {
  return value.replace(/\{(\w+)\}/g, (match, name: string) => variables[name] === undefined ? match : String(variables[name]))
}

type DetailCopy = {
  back: string; bookmark: string; saved: string; country: string; liquidity: string; risk: string; minimum: string
  overview: string; overviewOpened: string; memorandum: string; memorandumBody: string; memorandumOpened: string
  fee: string; revenueCycle: string; monthly: string; exitWindow: string; kycRequired: string; mpcSettlement: string; yieldWarning: string; investUsdt: string
  issuer: string; structure: string; referenceLocation: string; targetSize: string; settlement: string; thesis: string; cashFlow: string
  milestones: string; risks: string; reviewBefore: string; documents: string; illustrative: string; complete: string; next: string; planned: string; documentOpened: string
}

export const detailCopy: Record<AppLocale, DetailCopy> = {
  en: { back: 'Back', bookmark: 'Save project', saved: 'Project saved', country: 'United States', liquidity: 'liquidity', risk: 'risk', minimum: 'minimum', overview: 'Asset overview', overviewOpened: 'Asset overview opened', memorandum: 'Offering memorandum', memorandumBody: 'Structure, fees, exit terms and risk factors.', memorandumOpened: 'Offering memorandum opened', fee: 'Subscription fee', revenueCycle: 'Revenue cycle', monthly: 'Monthly', exitWindow: 'Exit window', kycRequired: 'KYC required before first allocation', mpcSettlement: 'USDT settlement to platform MPC wallet', yieldWarning: 'Projected yield is not guaranteed', investUsdt: 'Invest with USDT', issuer: 'Issuer / vehicle', structure: 'Structure', referenceLocation: 'Reference location', targetSize: 'Target size', settlement: 'Settlement', thesis: 'Investment thesis · Demo', cashFlow: 'Cash-flow basis', milestones: 'Key milestones', risks: 'Key risks', reviewBefore: 'Review before allocating', documents: 'Documents & reporting', illustrative: 'Illustrative materials', complete: 'Complete', next: 'Next', planned: 'Planned', documentOpened: '{name} opened in the Demo.' },
  'zh-CN': { back: '返回', bookmark: '收藏项目', saved: '项目已收藏', country: '美国', liquidity: '流动性', risk: '风险', minimum: '最低认购额', overview: '资产概览', overviewOpened: '已打开资产概览', memorandum: '发行备忘录', memorandumBody: '产品结构、费用、退出条款与风险因素。', memorandumOpened: '已打开发行备忘录', fee: '认购手续费', revenueCycle: '收益周期', monthly: '每月', exitWindow: '退出窗口', kycRequired: '首次认购前须完成 KYC', mpcSettlement: 'USDT 通过平台 MPC 钱包结算', yieldWarning: '预计收益不构成保证', investUsdt: '使用 USDT 投资', issuer: '发行方 / 载体', structure: '产品结构', referenceLocation: '参考地区', targetSize: '目标规模', settlement: '结算方式', thesis: '投资逻辑 · 演示', cashFlow: '现金流来源', milestones: '关键里程碑', risks: '主要风险', reviewBefore: '配置前请审阅', documents: '文件与报告', illustrative: '示意资料', complete: '已完成', next: '下一步', planned: '计划中', documentOpened: '已在演示中打开{name}。' },
  hi: { back: 'वापस', bookmark: 'परियोजना सहेजें', saved: 'परियोजना सहेजी गई', country: 'संयुक्त राज्य', liquidity: 'तरलता', risk: 'जोखिम', minimum: 'न्यूनतम', overview: 'परिसंपत्ति अवलोकन', overviewOpened: 'परिसंपत्ति अवलोकन खोला गया', memorandum: 'ऑफ़र ज्ञापन', memorandumBody: 'संरचना, शुल्क, निकास शर्तें और जोखिम कारक।', memorandumOpened: 'ऑफ़र ज्ञापन खोला गया', fee: 'सदस्यता शुल्क', revenueCycle: 'आय चक्र', monthly: 'मासिक', exitWindow: 'निकास विंडो', kycRequired: 'पहले आवंटन से पूर्व KYC आवश्यक', mpcSettlement: 'USDT का निपटान प्लेटफ़ॉर्म MPC वॉलेट में', yieldWarning: 'अनुमानित प्रतिफल की गारंटी नहीं है', investUsdt: 'USDT से निवेश करें', issuer: 'जारीकर्ता / वाहन', structure: 'संरचना', referenceLocation: 'संदर्भ स्थान', targetSize: 'लक्ष्य आकार', settlement: 'निपटान', thesis: 'निवेश तर्क · डेमो', cashFlow: 'नकदी-प्रवाह आधार', milestones: 'मुख्य पड़ाव', risks: 'मुख्य जोखिम', reviewBefore: 'आवंटन से पहले समीक्षा करें', documents: 'दस्तावेज़ और रिपोर्टिंग', illustrative: 'उदाहरण सामग्री', complete: 'पूर्ण', next: 'अगला', planned: 'नियोजित', documentOpened: '{name} डेमो में खोला गया।' },
  es: { back: 'Volver', bookmark: 'Guardar proyecto', saved: 'Proyecto guardado', country: 'Estados Unidos', liquidity: 'liquidez', risk: 'riesgo', minimum: 'mínimo', overview: 'Resumen del activo', overviewOpened: 'Resumen del activo abierto', memorandum: 'Memorando de oferta', memorandumBody: 'Estructura, comisiones, salida y factores de riesgo.', memorandumOpened: 'Memorando de oferta abierto', fee: 'Comisión de suscripción', revenueCycle: 'Ciclo de ingresos', monthly: 'Mensual', exitWindow: 'Ventana de salida', kycRequired: 'KYC obligatorio antes de la primera asignación', mpcSettlement: 'Liquidación USDT en el wallet MPC de la plataforma', yieldWarning: 'El rendimiento proyectado no está garantizado', investUsdt: 'Invertir con USDT', issuer: 'Emisor / vehículo', structure: 'Estructura', referenceLocation: 'Ubicación de referencia', targetSize: 'Tamaño objetivo', settlement: 'Liquidación', thesis: 'Tesis de inversión · Demo', cashFlow: 'Base del flujo de caja', milestones: 'Hitos principales', risks: 'Riesgos principales', reviewBefore: 'Revisar antes de asignar', documents: 'Documentos e informes', illustrative: 'Material ilustrativo', complete: 'Completado', next: 'Siguiente', planned: 'Planificado', documentOpened: '{name} abierto en la demo.' },
  ar: { back: 'رجوع', bookmark: 'حفظ المشروع', saved: 'تم حفظ المشروع', country: 'الولايات المتحدة', liquidity: 'السيولة', risk: 'المخاطر', minimum: 'الحد الأدنى', overview: 'نظرة عامة على الأصل', overviewOpened: 'تم فتح نظرة الأصل', memorandum: 'مذكرة الطرح', memorandumBody: 'الهيكل والرسوم وشروط الخروج وعوامل المخاطر.', memorandumOpened: 'تم فتح مذكرة الطرح', fee: 'رسوم الاكتتاب', revenueCycle: 'دورة الإيراد', monthly: 'شهري', exitWindow: 'نافذة الخروج', kycRequired: 'يلزم إكمال KYC قبل أول تخصيص', mpcSettlement: 'تسوية USDT في محفظة MPC للمنصة', yieldWarning: 'العائد المتوقع غير مضمون', investUsdt: 'استثمر باستخدام USDT', issuer: 'المُصدر / الكيان', structure: 'الهيكل', referenceLocation: 'الموقع المرجعي', targetSize: 'الحجم المستهدف', settlement: 'التسوية', thesis: 'منطق الاستثمار · تجريبي', cashFlow: 'أساس التدفق النقدي', milestones: 'المراحل الرئيسية', risks: 'المخاطر الرئيسية', reviewBefore: 'راجع قبل التخصيص', documents: 'المستندات والتقارير', illustrative: 'مواد توضيحية', complete: 'مكتمل', next: 'التالي', planned: 'مخطط', documentOpened: 'تم فتح {name} في العرض التجريبي.' },
  fr: { back: 'Retour', bookmark: 'Enregistrer le projet', saved: 'Projet enregistré', country: 'États-Unis', liquidity: 'liquidité', risk: 'risque', minimum: 'minimum', overview: "Vue d’ensemble de l’actif", overviewOpened: "Vue d’ensemble ouverte", memorandum: "Mémorandum d’offre", memorandumBody: 'Structure, frais, modalités de sortie et facteurs de risque.', memorandumOpened: "Mémorandum d’offre ouvert", fee: 'Frais de souscription', revenueCycle: 'Cycle de revenus', monthly: 'Mensuel', exitWindow: 'Fenêtre de sortie', kycRequired: 'KYC requis avant la première allocation', mpcSettlement: 'Règlement USDT vers le wallet MPC de la plateforme', yieldWarning: 'Le rendement projeté n’est pas garanti', investUsdt: 'Investir en USDT', issuer: 'Émetteur / véhicule', structure: 'Structure', referenceLocation: 'Lieu de référence', targetSize: 'Taille cible', settlement: 'Règlement', thesis: 'Thèse d’investissement · Démo', cashFlow: 'Base des flux de trésorerie', milestones: 'Étapes clés', risks: 'Risques principaux', reviewBefore: 'À examiner avant allocation', documents: 'Documents et reporting', illustrative: 'Documents illustratifs', complete: 'Terminé', next: 'Suivant', planned: 'Planifié', documentOpened: '{name} ouvert dans la démo.' },
  pt: { back: 'Voltar', bookmark: 'Salvar projeto', saved: 'Projeto salvo', country: 'Estados Unidos', liquidity: 'liquidez', risk: 'risco', minimum: 'mínimo', overview: 'Visão geral do ativo', overviewOpened: 'Visão geral aberta', memorandum: 'Memorando da oferta', memorandumBody: 'Estrutura, taxas, condições de saída e fatores de risco.', memorandumOpened: 'Memorando aberto', fee: 'Taxa de subscrição', revenueCycle: 'Ciclo de receita', monthly: 'Mensal', exitWindow: 'Janela de saída', kycRequired: 'KYC obrigatório antes da primeira alocação', mpcSettlement: 'Liquidação em USDT para a carteira MPC da plataforma', yieldWarning: 'O retorno projetado não é garantido', investUsdt: 'Investir com USDT', issuer: 'Emissor / veículo', structure: 'Estrutura', referenceLocation: 'Local de referência', targetSize: 'Tamanho-alvo', settlement: 'Liquidação', thesis: 'Tese de investimento · Demo', cashFlow: 'Base do fluxo de caixa', milestones: 'Marcos principais', risks: 'Riscos principais', reviewBefore: 'Revise antes de alocar', documents: 'Documentos e relatórios', illustrative: 'Materiais ilustrativos', complete: 'Concluído', next: 'Próximo', planned: 'Planejado', documentOpened: '{name} aberto na demo.' },
}

type OrderCopy = {
  review: string; amount: string; available: string; allocation: string; fee: string; total: string; enterAmount: string; balanceExceeded: string
  quoteExpired: string; quoteHeld: string; expiredBody: string; heldBody: string; refresh: string; confirmation: string; confirmationBody: string; confirmFirst: string
  recording: string; refreshToContinue: string; recordRequest: string; recordAllocation: string; successEyebrow: string; noExternal: string
  predictionSuccess: string; allocationSuccess: string; orderReference: string; executionState: string; demoOnly: string; nextGate: string
  partnerIntegration: string; eligibilitySettlement: string; viewReceipt: string; viewPortfolio: string
}

export const orderCopy: Record<AppLocale, OrderCopy> = {
  en: { review: 'Review order', amount: 'Investment amount', available: 'Available balance', allocation: 'Allocation', fee: 'Subscription fee', total: 'Total to lock', enterAmount: 'Enter an allocation amount.', balanceExceeded: 'Amount and fee exceed your available balance.', quoteExpired: 'Quote expired', quoteHeld: 'Quote held for {seconds}s', expiredBody: 'Refresh before confirming. No funds were locked.', heldBody: 'Price, fee and availability are held for this Demo preview.', refresh: 'Refresh', confirmation: 'Investment confirmation', confirmationBody: 'I understand this position may lose value and projected returns are not guaranteed.', confirmFirst: 'Confirm the risk disclosure before continuing.', recording: 'Recording Demo request…', refreshToContinue: 'Refresh quote to continue', recordRequest: 'Record Demo request', recordAllocation: 'Record Demo allocation', successEyebrow: 'DEMO REQUEST RECORDED', noExternal: 'No external order was placed.', predictionSuccess: '{name} remains read-only until distribution access, regional eligibility and account permissions are configured.', allocationSuccess: '{name} is stored as a prototype allocation intent. It does not alter balances, create a position or schedule settlement.', orderReference: 'Order reference', executionState: 'Execution state', demoOnly: 'Demo only', nextGate: 'Next production gate', partnerIntegration: 'Partner integration', eligibilitySettlement: 'Eligibility + settlement API', viewReceipt: 'View Demo receipt', viewPortfolio: 'View Demo portfolio' },
  'zh-CN': { review: '确认订单', amount: '投资金额', available: '可用余额', allocation: '认购金额', fee: '认购手续费', total: '锁定总额', enterAmount: '请输入投资金额。', balanceExceeded: '投资金额与手续费超过可用余额。', quoteExpired: '报价已过期', quoteHeld: '报价保留 {seconds} 秒', expiredBody: '确认前请刷新报价，当前未锁定任何资金。', heldBody: '本次演示预览暂时保留价格、费用与额度。', refresh: '刷新', confirmation: '投资风险确认', confirmationBody: '我理解该持仓可能亏损，预计收益不构成保证。', confirmFirst: '继续前请确认风险披露。', recording: '正在记录演示请求…', refreshToContinue: '刷新报价后继续', recordRequest: '记录演示请求', recordAllocation: '记录演示认购', successEyebrow: '演示请求已记录', noExternal: '未向外部提交任何订单。', predictionSuccess: '{name} 仍为只读，待分销权限、地区准入与账户权限配置完成后方可执行。', allocationSuccess: '{name} 已作为原型认购意向保存，不会改变余额、创建持仓或安排结算。', orderReference: '订单编号', executionState: '执行状态', demoOnly: '仅演示', nextGate: '下一生产条件', partnerIntegration: '合作方接口', eligibilitySettlement: '准入与结算接口', viewReceipt: '查看演示回执', viewPortfolio: '查看演示组合' },
  hi: { review: 'ऑर्डर की समीक्षा', amount: 'निवेश राशि', available: 'उपलब्ध शेष', allocation: 'आवंटन', fee: 'सदस्यता शुल्क', total: 'कुल लॉक राशि', enterAmount: 'आवंटन राशि दर्ज करें।', balanceExceeded: 'राशि और शुल्क उपलब्ध शेष से अधिक हैं।', quoteExpired: 'कोट समाप्त', quoteHeld: 'कोट {seconds} सेकंड के लिए सुरक्षित', expiredBody: 'पुष्टि से पहले रीफ़्रेश करें। कोई धन लॉक नहीं हुआ।', heldBody: 'इस डेमो पूर्वावलोकन के लिए मूल्य, शुल्क और उपलब्धता सुरक्षित हैं।', refresh: 'रीफ़्रेश', confirmation: 'निवेश पुष्टि', confirmationBody: 'मैं समझता हूँ कि मूल्य घट सकता है और अनुमानित प्रतिफल की गारंटी नहीं है।', confirmFirst: 'जारी रखने से पहले जोखिम प्रकटीकरण स्वीकार करें।', recording: 'डेमो अनुरोध दर्ज हो रहा है…', refreshToContinue: 'जारी रखने के लिए कोट रीफ़्रेश करें', recordRequest: 'डेमो अनुरोध दर्ज करें', recordAllocation: 'डेमो आवंटन दर्ज करें', successEyebrow: 'डेमो अनुरोध दर्ज', noExternal: 'कोई बाहरी ऑर्डर नहीं भेजा गया।', predictionSuccess: 'वितरण पहुँच, क्षेत्रीय पात्रता और खाते की अनुमति कॉन्फ़िगर होने तक {name} केवल-पठन रहेगा।', allocationSuccess: '{name} को प्रोटोटाइप आवंटन इच्छा के रूप में सहेजा गया है। इससे शेष या स्थिति नहीं बदलती।', orderReference: 'ऑर्डर संदर्भ', executionState: 'निष्पादन स्थिति', demoOnly: 'केवल डेमो', nextGate: 'अगला उत्पादन चरण', partnerIntegration: 'साझेदार एकीकरण', eligibilitySettlement: 'पात्रता + निपटान API', viewReceipt: 'डेमो रसीद देखें', viewPortfolio: 'डेमो पोर्टफोलियो देखें' },
  es: { review: 'Revisar orden', amount: 'Importe de inversión', available: 'Saldo disponible', allocation: 'Asignación', fee: 'Comisión de suscripción', total: 'Total a bloquear', enterAmount: 'Introduce un importe de inversión.', balanceExceeded: 'El importe y la comisión superan el saldo disponible.', quoteExpired: 'Cotización vencida', quoteHeld: 'Cotización válida durante {seconds}s', expiredBody: 'Actualiza antes de confirmar. No se bloquearon fondos.', heldBody: 'Precio, comisión y disponibilidad se mantienen para esta vista demo.', refresh: 'Actualizar', confirmation: 'Confirmación de inversión', confirmationBody: 'Entiendo que la posición puede perder valor y que los rendimientos no están garantizados.', confirmFirst: 'Confirma la divulgación de riesgos antes de continuar.', recording: 'Registrando solicitud demo…', refreshToContinue: 'Actualiza la cotización para continuar', recordRequest: 'Registrar solicitud demo', recordAllocation: 'Registrar asignación demo', successEyebrow: 'SOLICITUD DEMO REGISTRADA', noExternal: 'No se envió ninguna orden externa.', predictionSuccess: '{name} seguirá en modo lectura hasta configurar distribución, elegibilidad y permisos.', allocationSuccess: '{name} se guarda como intención de asignación. No altera saldos ni crea posiciones.', orderReference: 'Referencia de orden', executionState: 'Estado de ejecución', demoOnly: 'Solo demo', nextGate: 'Siguiente requisito', partnerIntegration: 'Integración del socio', eligibilitySettlement: 'API de elegibilidad y liquidación', viewReceipt: 'Ver recibo demo', viewPortfolio: 'Ver cartera demo' },
  ar: { review: 'مراجعة الطلب', amount: 'مبلغ الاستثمار', available: 'الرصيد المتاح', allocation: 'التخصيص', fee: 'رسوم الاكتتاب', total: 'إجمالي الحجز', enterAmount: 'أدخل مبلغ التخصيص.', balanceExceeded: 'المبلغ والرسوم يتجاوزان الرصيد المتاح.', quoteExpired: 'انتهت صلاحية السعر', quoteHeld: 'السعر محفوظ لمدة {seconds} ثانية', expiredBody: 'حدّث قبل التأكيد. لم يتم حجز أي أموال.', heldBody: 'السعر والرسوم والتوافر محفوظة لمعاينة العرض التجريبي.', refresh: 'تحديث', confirmation: 'تأكيد الاستثمار', confirmationBody: 'أفهم أن المركز قد يخسر قيمته وأن العوائد المتوقعة غير مضمونة.', confirmFirst: 'أكد الإفصاح عن المخاطر قبل المتابعة.', recording: 'جارٍ تسجيل الطلب التجريبي…', refreshToContinue: 'حدّث السعر للمتابعة', recordRequest: 'تسجيل طلب تجريبي', recordAllocation: 'تسجيل تخصيص تجريبي', successEyebrow: 'تم تسجيل الطلب التجريبي', noExternal: 'لم يتم إرسال أي طلب خارجي.', predictionSuccess: 'يبقى {name} للقراءة فقط حتى ضبط التوزيع والأهلية والأذونات.', allocationSuccess: 'تم حفظ {name} كنموذج لنية التخصيص، دون تغيير الرصيد أو إنشاء مركز.', orderReference: 'مرجع الطلب', executionState: 'حالة التنفيذ', demoOnly: 'تجريبي فقط', nextGate: 'شرط الإنتاج التالي', partnerIntegration: 'تكامل الشريك', eligibilitySettlement: 'واجهة الأهلية والتسوية', viewReceipt: 'عرض الإيصال التجريبي', viewPortfolio: 'عرض المحفظة التجريبية' },
  fr: { review: 'Vérifier l’ordre', amount: 'Montant investi', available: 'Solde disponible', allocation: 'Allocation', fee: 'Frais de souscription', total: 'Total à bloquer', enterAmount: 'Saisissez un montant d’allocation.', balanceExceeded: 'Le montant et les frais dépassent le solde disponible.', quoteExpired: 'Cotation expirée', quoteHeld: 'Cotation maintenue {seconds}s', expiredBody: 'Actualisez avant de confirmer. Aucun fonds n’a été bloqué.', heldBody: 'Prix, frais et disponibilité sont maintenus pour cet aperçu démo.', refresh: 'Actualiser', confirmation: 'Confirmation d’investissement', confirmationBody: 'Je comprends que la position peut perdre de la valeur et que le rendement n’est pas garanti.', confirmFirst: 'Confirmez les risques avant de continuer.', recording: 'Enregistrement de la demande démo…', refreshToContinue: 'Actualiser la cotation pour continuer', recordRequest: 'Enregistrer la demande démo', recordAllocation: 'Enregistrer l’allocation démo', successEyebrow: 'DEMANDE DÉMO ENREGISTRÉE', noExternal: 'Aucun ordre externe n’a été envoyé.', predictionSuccess: '{name} reste en lecture seule jusqu’à la configuration de la distribution, de l’éligibilité et des autorisations.', allocationSuccess: '{name} est enregistré comme intention d’allocation. Aucun solde ni position n’est modifié.', orderReference: 'Référence de l’ordre', executionState: 'État d’exécution', demoOnly: 'Démo uniquement', nextGate: 'Prochaine condition', partnerIntegration: 'Intégration partenaire', eligibilitySettlement: 'API éligibilité + règlement', viewReceipt: 'Voir le reçu démo', viewPortfolio: 'Voir le portefeuille démo' },
  pt: { review: 'Revisar ordem', amount: 'Valor do investimento', available: 'Saldo disponível', allocation: 'Alocação', fee: 'Taxa de subscrição', total: 'Total a bloquear', enterAmount: 'Insira um valor de alocação.', balanceExceeded: 'O valor e a taxa excedem o saldo disponível.', quoteExpired: 'Cotação expirada', quoteHeld: 'Cotação mantida por {seconds}s', expiredBody: 'Atualize antes de confirmar. Nenhum fundo foi bloqueado.', heldBody: 'Preço, taxa e disponibilidade são mantidos nesta prévia demo.', refresh: 'Atualizar', confirmation: 'Confirmação do investimento', confirmationBody: 'Entendo que a posição pode perder valor e que o retorno não é garantido.', confirmFirst: 'Confirme a divulgação de riscos antes de continuar.', recording: 'Registrando solicitação demo…', refreshToContinue: 'Atualize a cotação para continuar', recordRequest: 'Registrar solicitação demo', recordAllocation: 'Registrar alocação demo', successEyebrow: 'SOLICITAÇÃO DEMO REGISTRADA', noExternal: 'Nenhuma ordem externa foi enviada.', predictionSuccess: '{name} permanecerá somente leitura até configurar distribuição, elegibilidade e permissões.', allocationSuccess: '{name} foi salvo como intenção de alocação. Não altera saldos nem cria posição.', orderReference: 'Referência da ordem', executionState: 'Estado da execução', demoOnly: 'Somente demo', nextGate: 'Próxima condição', partnerIntegration: 'Integração do parceiro', eligibilitySettlement: 'API de elegibilidade e liquidação', viewReceipt: 'Ver recibo demo', viewPortfolio: 'Ver portfólio demo' },
}

type AccountCopy = {
  thisMonth: string; score: string; scoreBody: string; today: string; days30: string; cash: string; reserve: string
  overview: string; positions: string; income: string; history: string; globalStocks: string; availableUsdt: string
  aiRebalance: string; rebalanceBody: string; riskEngine: string; riskBody: string; nextDistribution: string
  networks: string; availableBalance: string; computePositions: string; activeUnits: string; rwaPositions: string; usdtValue: string
  deposit: string; investment: string; reward: string; computeRevenue: string
  aiAdvisor: string; aiHeading: string; userPrompt: string; balanced: string; reviewPlan: string; askPlaceholder: string; analysisGenerated: string
  verified: string; passkeyEnabled: string; inviteEarn: string; ordersSettlements: string; realIssue: string; emailPush: string
  verifyLinks: string; languageNotifications: string; publicSession: string; closeAccount: string; signedOut: string
}

export const accountCopy: Record<AppLocale, AccountCopy> = {
  en: { thisMonth: 'this month', score: 'AI Portfolio Score', scoreBody: 'Balanced exposure with moderate liquidity risk.', today: 'Today', days30: '30 days', cash: 'Cash', reserve: 'reserve', overview: 'Overview', positions: 'Positions', income: 'Income', history: 'History', globalStocks: 'Global Stocks', availableUsdt: 'Available USDT', aiRebalance: 'AI Rebalance', rebalanceBody: 'One opportunity needs your attention.', riskEngine: 'Risk engine', riskBody: 'Compute utilization is strong. RWA lockup is within target. Stock concentration is approaching the preferred limit.', nextDistribution: 'Next expected distribution', networks: 'USDT networks', availableBalance: 'Available balance', computePositions: 'Compute Positions', activeUnits: '2 active units', rwaPositions: 'RWA Positions', usdtValue: 'USDT value', deposit: 'Deposit', investment: 'Investment', reward: 'Reward', computeRevenue: 'Compute revenue', aiAdvisor: 'AI Investment Advisor', aiHeading: 'Ask before you allocate.', userPrompt: 'Help me allocate 10,000 USDT.', balanced: 'Balanced allocation', reviewPlan: 'Review allocation plan', askPlaceholder: 'Ask about risk or allocation', analysisGenerated: 'AI analysis generated', verified: 'Verified', passkeyEnabled: 'Passkey enabled', inviteEarn: 'Invite and earn', ordersSettlements: 'Orders and settlements', realIssue: 'Help with a real issue', emailPush: 'Email, push and community', verifyLinks: 'Verify links and report scams', languageNotifications: 'Language and notifications', publicSession: 'Public browsing session', closeAccount: 'Request account closure', signedOut: 'Demo session signed out.' },
  'zh-CN': { thisMonth: '本月', score: 'AI 组合评分', scoreBody: '配置较均衡，流动性风险中等。', today: '今日', days30: '近 30 天', cash: '现金', reserve: '储备', overview: '概览', positions: '持仓', income: '收益', history: '历史', globalStocks: '全球股票', availableUsdt: '可用 USDT', aiRebalance: 'AI 再平衡', rebalanceBody: '有 1 项机会需要你关注。', riskEngine: '风险引擎', riskBody: '算力利用率保持强劲，RWA 锁定期符合目标，股票集中度正在接近偏好上限。', nextDistribution: '下一笔预计收益', networks: 'USDT 网络', availableBalance: '可用余额', computePositions: '算力持仓', activeUnits: '2 个活跃份额', rwaPositions: 'RWA 持仓', usdtValue: 'USDT 估值', deposit: '充值', investment: '投资', reward: '收益', computeRevenue: '算力收益', aiAdvisor: 'AI 投资助手', aiHeading: '配置之前，先问 AI。', userPrompt: '帮我配置 10,000 USDT。', balanced: '均衡配置方案', reviewPlan: '查看配置方案', askPlaceholder: '询问风险或资产配置', analysisGenerated: 'AI 分析已生成', verified: '已认证', passkeyEnabled: '通行密钥已启用', inviteEarn: '邀请并赚取奖励', ordersSettlements: '订单与结算', realIssue: '处理真实问题', emailPush: '邮件、推送与社群', verifyLinks: '验证链接并举报诈骗', languageNotifications: '语言与通知', publicSession: '公开浏览会话', closeAccount: '申请关闭账户', signedOut: '演示会话已退出。' },
  hi: { thisMonth: 'इस माह', score: 'AI पोर्टफोलियो स्कोर', scoreBody: 'मध्यम तरलता जोखिम के साथ संतुलित एक्सपोज़र।', today: 'आज', days30: '30 दिन', cash: 'नकद', reserve: 'आरक्षित', overview: 'अवलोकन', positions: 'स्थितियाँ', income: 'आय', history: 'इतिहास', globalStocks: 'वैश्विक शेयर', availableUsdt: 'उपलब्ध USDT', aiRebalance: 'AI पुनर्संतुलन', rebalanceBody: 'एक अवसर पर आपका ध्यान आवश्यक है।', riskEngine: 'जोखिम इंजन', riskBody: 'कंप्यूट उपयोग मजबूत है, RWA लॉकअप लक्ष्य में है और शेयर एकाग्रता सीमा के पास है।', nextDistribution: 'अगला अपेक्षित वितरण', networks: 'USDT नेटवर्क', availableBalance: 'उपलब्ध शेष', computePositions: 'कंप्यूट स्थितियाँ', activeUnits: '2 सक्रिय इकाइयाँ', rwaPositions: 'RWA स्थितियाँ', usdtValue: 'USDT मूल्य', deposit: 'जमा', investment: 'निवेश', reward: 'प्रतिफल', computeRevenue: 'कंप्यूट आय', aiAdvisor: 'AI निवेश सलाहकार', aiHeading: 'आवंटन से पहले पूछें।', userPrompt: '10,000 USDT आवंटित करने में मदद करें।', balanced: 'संतुलित आवंटन', reviewPlan: 'आवंटन योजना देखें', askPlaceholder: 'जोखिम या आवंटन पूछें', analysisGenerated: 'AI विश्लेषण तैयार', verified: 'सत्यापित', passkeyEnabled: 'पासकी सक्रिय', inviteEarn: 'आमंत्रित करें और कमाएँ', ordersSettlements: 'ऑर्डर और निपटान', realIssue: 'वास्तविक समस्या में सहायता', emailPush: 'ईमेल, पुश और समुदाय', verifyLinks: 'लिंक सत्यापित करें और धोखाधड़ी रिपोर्ट करें', languageNotifications: 'भाषा और सूचनाएँ', publicSession: 'सार्वजनिक ब्राउज़िंग सत्र', closeAccount: 'खाता बंद करने का अनुरोध', signedOut: 'डेमो सत्र समाप्त।' },
  es: { thisMonth: 'este mes', score: 'Puntuación IA de la cartera', scoreBody: 'Exposición equilibrada con riesgo de liquidez moderado.', today: 'Hoy', days30: '30 días', cash: 'Efectivo', reserve: 'reserva', overview: 'Resumen', positions: 'Posiciones', income: 'Ingresos', history: 'Historial', globalStocks: 'Acciones globales', availableUsdt: 'USDT disponible', aiRebalance: 'Reequilibrio IA', rebalanceBody: 'Una oportunidad requiere tu atención.', riskEngine: 'Motor de riesgo', riskBody: 'La utilización de cómputo es sólida, el bloqueo RWA está dentro del objetivo y la concentración bursátil se acerca al límite.', nextDistribution: 'Próxima distribución prevista', networks: 'Redes USDT', availableBalance: 'Saldo disponible', computePositions: 'Posiciones de cómputo', activeUnits: '2 unidades activas', rwaPositions: 'Posiciones RWA', usdtValue: 'valor en USDT', deposit: 'Depósito', investment: 'Inversión', reward: 'Rendimiento', computeRevenue: 'Ingreso de cómputo', aiAdvisor: 'Asesor de inversión IA', aiHeading: 'Pregunta antes de asignar.', userPrompt: 'Ayúdame a asignar 10.000 USDT.', balanced: 'Asignación equilibrada', reviewPlan: 'Revisar plan', askPlaceholder: 'Pregunta por riesgo o asignación', analysisGenerated: 'Análisis IA generado', verified: 'Verificado', passkeyEnabled: 'Passkey activa', inviteEarn: 'Invita y gana', ordersSettlements: 'Órdenes y liquidaciones', realIssue: 'Ayuda con un problema real', emailPush: 'Email, push y comunidad', verifyLinks: 'Verifica enlaces y reporta fraudes', languageNotifications: 'Idioma y notificaciones', publicSession: 'Sesión de navegación pública', closeAccount: 'Solicitar cierre de cuenta', signedOut: 'Sesión demo cerrada.' },
  ar: { thisMonth: 'هذا الشهر', score: 'تقييم المحفظة بالذكاء الاصطناعي', scoreBody: 'تعرض متوازن مع مخاطر سيولة متوسطة.', today: 'اليوم', days30: '30 يومًا', cash: 'نقد', reserve: 'احتياطي', overview: 'نظرة عامة', positions: 'المراكز', income: 'الدخل', history: 'السجل', globalStocks: 'أسهم عالمية', availableUsdt: 'USDT المتاح', aiRebalance: 'إعادة موازنة بالذكاء الاصطناعي', rebalanceBody: 'فرصة واحدة تحتاج إلى انتباهك.', riskEngine: 'محرك المخاطر', riskBody: 'استخدام الحوسبة قوي، وفترة RWA ضمن الهدف، وتركيز الأسهم يقترب من الحد المفضل.', nextDistribution: 'التوزيع المتوقع التالي', networks: 'شبكات USDT', availableBalance: 'الرصيد المتاح', computePositions: 'مراكز الحوسبة', activeUnits: 'وحدتان نشطتان', rwaPositions: 'مراكز RWA', usdtValue: 'القيمة بـ USDT', deposit: 'إيداع', investment: 'استثمار', reward: 'عائد', computeRevenue: 'إيراد الحوسبة', aiAdvisor: 'مستشار الاستثمار بالذكاء الاصطناعي', aiHeading: 'اسأل قبل التخصيص.', userPrompt: 'ساعدني في تخصيص 10,000 USDT.', balanced: 'تخصيص متوازن', reviewPlan: 'مراجعة الخطة', askPlaceholder: 'اسأل عن المخاطر أو التخصيص', analysisGenerated: 'تم إنشاء تحليل الذكاء الاصطناعي', verified: 'موثّق', passkeyEnabled: 'مفتاح المرور مفعّل', inviteEarn: 'ادعُ واكسب', ordersSettlements: 'الطلبات والتسويات', realIssue: 'مساعدة في مشكلة فعلية', emailPush: 'البريد والدفع والمجتمع', verifyLinks: 'تحقق من الروابط وأبلغ عن الاحتيال', languageNotifications: 'اللغة والإشعارات', publicSession: 'جلسة تصفح عامة', closeAccount: 'طلب إغلاق الحساب', signedOut: 'تم تسجيل الخروج من الجلسة التجريبية.' },
  fr: { thisMonth: 'ce mois', score: 'Score IA du portefeuille', scoreBody: 'Exposition équilibrée avec un risque de liquidité modéré.', today: 'Aujourd’hui', days30: '30 jours', cash: 'Trésorerie', reserve: 'réserve', overview: 'Vue d’ensemble', positions: 'Positions', income: 'Revenus', history: 'Historique', globalStocks: 'Actions mondiales', availableUsdt: 'USDT disponible', aiRebalance: 'Rééquilibrage IA', rebalanceBody: 'Une opportunité nécessite votre attention.', riskEngine: 'Moteur de risque', riskBody: 'L’utilisation du calcul est solide, le blocage RWA est conforme et la concentration actions approche de la limite.', nextDistribution: 'Prochaine distribution estimée', networks: 'Réseaux USDT', availableBalance: 'Solde disponible', computePositions: 'Positions de calcul', activeUnits: '2 unités actives', rwaPositions: 'Positions RWA', usdtValue: 'valeur USDT', deposit: 'Dépôt', investment: 'Investissement', reward: 'Revenu', computeRevenue: 'Revenu de calcul', aiAdvisor: 'Conseiller en investissement IA', aiHeading: 'Demandez avant d’allouer.', userPrompt: 'Aidez-moi à allouer 10 000 USDT.', balanced: 'Allocation équilibrée', reviewPlan: 'Examiner le plan', askPlaceholder: 'Question sur le risque ou l’allocation', analysisGenerated: 'Analyse IA générée', verified: 'Vérifié', passkeyEnabled: 'Passkey activée', inviteEarn: 'Inviter et gagner', ordersSettlements: 'Ordres et règlements', realIssue: 'Aide sur un problème réel', emailPush: 'Email, push et communauté', verifyLinks: 'Vérifier les liens et signaler les fraudes', languageNotifications: 'Langue et notifications', publicSession: 'Session de navigation publique', closeAccount: 'Demander la clôture du compte', signedOut: 'Session démo déconnectée.' },
  pt: { thisMonth: 'este mês', score: 'Pontuação de IA do portfólio', scoreBody: 'Exposição equilibrada com risco moderado de liquidez.', today: 'Hoje', days30: '30 dias', cash: 'Caixa', reserve: 'reserva', overview: 'Visão geral', positions: 'Posições', income: 'Renda', history: 'Histórico', globalStocks: 'Ações globais', availableUsdt: 'USDT disponível', aiRebalance: 'Rebalanceamento por IA', rebalanceBody: 'Uma oportunidade precisa da sua atenção.', riskEngine: 'Motor de risco', riskBody: 'A utilização de computação está forte, o bloqueio RWA está na meta e a concentração em ações se aproxima do limite.', nextDistribution: 'Próxima distribuição prevista', networks: 'Redes USDT', availableBalance: 'Saldo disponível', computePositions: 'Posições de computação', activeUnits: '2 unidades ativas', rwaPositions: 'Posições RWA', usdtValue: 'valor em USDT', deposit: 'Depósito', investment: 'Investimento', reward: 'Retorno', computeRevenue: 'Receita de computação', aiAdvisor: 'Consultor de investimentos de IA', aiHeading: 'Pergunte antes de alocar.', userPrompt: 'Ajude-me a alocar 10.000 USDT.', balanced: 'Alocação equilibrada', reviewPlan: 'Revisar plano', askPlaceholder: 'Pergunte sobre risco ou alocação', analysisGenerated: 'Análise de IA gerada', verified: 'Verificado', passkeyEnabled: 'Passkey ativada', inviteEarn: 'Convide e ganhe', ordersSettlements: 'Ordens e liquidações', realIssue: 'Ajuda com um problema real', emailPush: 'Email, push e comunidade', verifyLinks: 'Verifique links e denuncie fraudes', languageNotifications: 'Idioma e notificações', publicSession: 'Sessão de navegação pública', closeAccount: 'Solicitar encerramento da conta', signedOut: 'Sessão demo encerrada.' },
}
