export const LEDGER_ERROR_CODES = {
  WITHDRAWAL_NOT_FOUND: 'LEDGER_WITHDRAWAL_NOT_FOUND',
  WITHDRAWAL_STATE_INVALID: 'LEDGER_WITHDRAWAL_STATE_INVALID',
  CHAIN_TRANSACTION_UNCONFIRMED: 'LEDGER_CHAIN_TRANSACTION_UNCONFIRMED',
  ACCOUNT_NOT_FOUND: 'LEDGER_ACCOUNT_NOT_FOUND',
  RECONCILIATION_INPUT_INVALID: 'LEDGER_RECONCILIATION_INPUT_INVALID',
  ADJUSTMENT_NOT_FOUND: 'LEDGER_ADJUSTMENT_NOT_FOUND',
  ADJUSTMENT_STATE_INVALID: 'LEDGER_ADJUSTMENT_STATE_INVALID',
  ADJUSTMENT_SELF_APPROVAL_FORBIDDEN: 'LEDGER_ADJUSTMENT_SELF_APPROVAL_FORBIDDEN',
} as const
